let links = [
    {
        href: "/discord.html",
        tag: ".gg URL Discord",
        title: "Serveur Discord",
        svg: "/assets/svg/trademark/discord.svg",
    },
    {
        href: "/discord/voc.html",
        tag: ".gg URL Discord",
        title: "Salon vocal Discord",
        svg: "/assets/svg/telephone.svg",
    },
    {
        href: "/discord/tempvoc.html",
        tag: ".gg URL Discord",
        title: "Salon vocal invité Discord",
        svg: "/assets/svg/telephone.svg",
    },
    {
        href: "/discord/api.html",
        tag: ".gg Discord Outils",
        title: "API Discord",
        svg: "/assets/svg/telephone.svg",
    },
    {
        href: "/discord/login.html",
        tag: ".gg Discord Outils",
        title: "Exemple d'API Discord login",
        svg: "/assets/svg/trademark/discord.svg",
    },
    {
        href: "https://play.Altherneum.fr",
        tag: "URL",
        title: "Serveur Minecraft",
        svg: "/assets/svg/trademark/minecraft.svg",
    },
    {
        href: "/",
        tag: "URL",
        title: "Accueil",
        svg: "/assets/svg/home.svg",
    },
    {
        href: "/settings.html",
        tag: "Outils URL",
        title: "Paramètres (Settings)",
        svg: "/assets/svg/settings.svg",
    },
    {
        href: "/outils/liens.html",
        svg: "/assets/svg/link.svg",
        tag: "URL Admin Cours ReadMe Outils",
        title: "Liste de liens utiles",
    },
    {
        href: "/github/statistiques.html",
        tag: "Github ReadMe Outils",
        title: "Statistiques Github",
        svg: "/assets/svg/app-gear.svg",
    },
    {
        href: "/github/contribuer.html",
        tag: "Github ReadMe",
        title: "Comment contribuer sur github ?",
        svg: "/assets/svg/help-question.svg",
    },
    {
        href: "/github/support.html",
        tag: "Github ReadMe",
        title: "Support d'aide",
        svg: "/assets/svg/help-question.svg",
    },
    {
        href: "/github/security.html",
        tag: "Github ReadMe",
        title: "Sécurité (Security)",
        svg: "/assets/svg/password.svg",
    },
    {
        href: "/github/license.html",
        tag: "Github ReadMe",
        title: "License Apache",
        svg: "/assets/svg/scroll-text.svg",
    },
    {
        href: "/github/code_of_conduct.html",
        tag: "Github ReadMe",
        title: "Code de conduite",
        svg: "/assets/svg/administrator.svg",
    },
    {
        href: "/github/issues.html",
        tag: "Github Outils",
        title: "Erreurs / Issues list Github",
        svg: "/assets/svg/issue.svg",
    },
    {
        href: "/github/contributeur.html",
        tag: "Github Outils",
        title: "Contributeurs Github",
        svg: "/assets/svg/people.svg",
    },
    {
        href: "/outils/matrice.html",
        tag: "Outils",
        title: "Matrice / Matrix",
        svg: "/assets/svg/matrix.svg",
    },
    {
        href: "/outils/matrice-windows.html",
        tag: "Outils",
        title: "Matrice / Matrix Windows",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/outils/ping.html",
        tag: "Outils Web Network",
        title: "Ping",
        svg: "/assets/svg/network.svg",
    },
    {
        href: "/outils/cube.html",
        tag: "Outils",
        title: "Cube & Sphère (Sphere) 3D",
        svg: "/assets/svg/cube.svg",
    },
    {
        href: "/outils/console.html",
        tag: "Outils",
        title: "Console",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/outils/rss.html",
        tag: "Outils RSS",
        title: "Flux RSS",
        svg: "/assets/svg/languages/rss.svg",
    },
    {
        href: "/games/shopTitans.html",
        tag: "Jeux Outils",
        title: "ShopTitans",
        svg: "/assets/image/ShopTitans.webp",
    },
    {
        href: "/games/minesweeper.html",
        tag: "Jeux",
        title: "MineSweeper (Démineur)",
        svg: "/assets/svg/bomb.svg",
    },
    {
        href: "/games/cookie.html",
        tag: "Jeux",
        title: "Cookie clicker",
        svg: "/assets/svg/cookie.svg",
    },
    {
        href: "/games/fruits.html",
        tag: "Jeux",
        title: "Suika game",
        svg: "/assets/svg/game.svg",
    },
    {
        href: "/rss.rss",
        tag: "RSS",
        title: "Fichier RSS.rss",
        svg: "/assets/svg/file-wired.svg",
    },
    {
        href: "/outils/caesar.html",
        tag: "Outils OpSec",
        title: "Chiffrement par décalage (Caesar / César)",
        svg: "/assets/svg/password.svg",
    },
    {
        href: "/outils/vigenere.html",
        tag: "Outils OpSec",
        title: "Chiffre de Vigenère",
        svg: "/assets/svg/password.svg",
    },
    {
        href: "/outils/base64.html",
        tag: "Outils OpSec",
        title: "Base64",
        svg: "/assets/svg/password.svg",
    },
    {
        href: "/outils/logger.html",
        tag: "Outils Web Network IP",
        title: "IP v4 v6 logger & browser scan",
        svg: "/assets/svg/ip.svg",
    },
    {
        href: "/outils/noise.html",
        tag: "Outils",
        title: "TV-noise",
        svg: "/assets/svg/tv2.svg",
    },
    {
        href: "/admin/contact.html",
        tag: "Admin",
        title: "Contacter l'administrateur du projet",
        svg: "/assets/svg/contact.svg",
    },
    {
        href: "/admin/software.html",
        tag: "Admin Outils URL",
        title: "Software de l'administrateur du projet (Windows, Arch, et logiciels)",
        svg: "/assets/svg/computer-configuration.svg",
    },
    {
        href: "/admin/hardware.html",
        tag: "Admin Outils URL",
        title: "HardWare (Matériel) de l'administrateur du projet",
        svg: "/assets/svg/gpu.svg",
    },
    {
        href: "/admin/film.html",
        tag: "Admin",
        title: "Les films conseillés par l'administrateur d'Altherneum",
        svg: "/assets/svg/film.svg",
    },
    {
        href: "/admin/music.html",
        tag: "Admin",
        title: "Musiques conseillés par l'administrateur d'Altherneum (Music)",
        svg: "/assets/svg/music.svg",
    },
    {
        href: "/admin/video.html",
        tag: "Admin",
        title: "Vidéos conseillés par l'administrateur d'Altherneum (YouTube)",
        svg: "/assets/svg/tv2.svg",
    },
    {
        href: "/admin/series.html",
        tag: "Admin",
        title: "Séries conseillés par l'administrateur d'Altherneum (Series)",
        svg: "/assets/svg/tv.svg",
    },
    {
        href: "/admin/animes.html",
        tag: "Admin",
        title: "Animes conseillés par l'administrateur d'Altherneum (Animés)",
        svg: "/assets/svg/draw.svg",
    },
    {
        href: "/admin/to-watch.html",
        tag: "Admin",
        title: "Animes (Animés), Films, Séries (Series) À voir de l'administrateur d'Altherneum",
        svg: "/assets/svg/help-question.svg",
    },
    {
        href: "/admin/donation.html",
        tag: "Admin Crypto",
        title: "Donation pour l'administrateur d'Altherneum",
        svg: "/assets/svg/donation.svg",
    },
    {
        href: "/admin/note.html",
        tag: "Admin ReadMe Cours",
        title: "Notes en cours de l'administrateur d'Altherneum",
        svg: "/assets/svg/note.svg",
    },
    {
        href: "https://github.com/Altherneum/",
        tag: "Repo Github URL",
        title: "Github organisation",
        svg: "/assets/svg/trademark/organisation.svg",
    },
    {
        href: "/404.html",
        tag: "Web",
        title: "Erreur 404",
        svg: "/assets/svg/link-broken.svg",
    },
    {
        href: "/github/readme.html",
        tag: "Github ReadMe",
        title: "ReadMe Github",
        svg: "/assets/svg/note.svg",
    },
    {
        href: "/github/altherneum.github.io.html",
        tag: "Repo Github ReadMe Web",
        title: "Repo du site Altherneum.github.io",
        svg: "/assets/svg/trademark/repo.svg",
    },
    {
        href: "/github/.github.html",
        tag: "Repo Github ReadMe Cours",
        title: "Repo des notes .github",
        svg: "/assets/svg/trademark/repo.svg",
    },
    {
        href: "/github/plugin.html",
        tag: "Repo Github ReadMe",
        title: "Repo du plugin (MC)",
        svg: "/assets/svg/trademark/repo.svg",
    },
    {
        href: "/github/resourcePack.html",
        tag: "Repo Github ReadMe",
        title: "Repo du resource pack",
        svg: "/assets/svg/trademark/repo.svg",
    },
    {
        href: "/github/bot.html",
        tag: "Repo Github ReadMe",
        title: "Repo bot (Discord)",
        svg: "/assets/svg/trademark/repo.svg",
    },
    {
        href: "/github/server.html",
        tag: "Repo Github ReadMe",
        title: "Repo du serveur",
        svg: "/assets/svg/trademark/repo.svg",
    },
    {
        href: "/cours/markdown.html",
        tag: "Cours",
        title: "MarkDown .md",
        svg: "/assets/svg/languages/markdown.svg",
    },
    {
        href: "/cours/markdown-listing.html",
        tag: "Outils",
        title: "MarkDown tester",
        svg: "/assets/svg/languages/markdown.svg",
    },
    {
        href: "/cours/github-readme.html",
        tag: "Github ReadMe",
        title: "ReadMe de Github (EN)",
        svg: "/assets/svg/trademark/github.svg",
    },
    {
        href: "/cours/fibre.html",
        tag: "Cours Network",
        title: "Fibre optique",
        svg: "/assets/svg/cables-cable.svg",
    },
    {
        href: "/cours/active-directory.html",
        tag: "Cours Windows OS",
        title: "Active directory Windows",
        svg: "/assets/svg/server.svg",
    },
    {
        href: "/cours/dns.html",
        tag: "Cours Windows Network",
        title: "DNS Windows server",
        svg: "/assets/svg/server.svg",
    },
    {
        href: "/cours/enterprise-network.html",
        tag: "Cours Network",
        title: "Réseaux d'entreprise avec domaine Windows",
        svg: "/assets/svg/network.svg",
    },
    {
        href: "/cours/ethernet.html",
        tag: "Cours Network",
        title: "Câbles Ethernet et leurs catégories",
        svg: "/assets/svg/ethernet.svg",
    },
    {
        href: "/cours/html.html",
        tag: "Cours Web",
        title: "HTML",
        svg: "/assets/svg/languages/html.svg",
    },
    {
        href: "/cours/css.html",
        tag: "Cours Web",
        title: "CSS",
        svg: "/assets/svg/languages/css.svg",
    },
    {
        href: "/cours/js.html",
        tag: "Cours Web",
        title: "JS",
        svg: "/assets/svg/languages/js.svg",
    },
    {
        href: "/cours/php.html",
        tag: "Cours Web",
        title: "PHP",
        svg: "/assets/svg/languages/php.svg",
    },
    {
        href: "/cours/binaire.html",
        tag: "Cours",
        title: "Binaire",
        svg: "/assets/svg/matrix.svg",
    },
    {
        href: "/cours/forkBomb.html",
        tag: "Cours CMD OS Linux",
        title: "Fork bomb Windows & Linux",
        svg: "/assets/svg/bomb.svg",
    },
    {
        href: "/cours/google-dorks.html",
        tag: "Cours Web Google",
        title: "Google et les Google dorks",
        svg: "/assets/svg/note.svg",
    },
    {
        href: "/cours/google-doodle.html",
        tag: "Cours Web Google",
        title: "Liste des doodles Google",
        svg: "/assets/svg/note.svg",
    },
    {
        href: "/cours/hyper-v.html",
        tag: "Cours OS Windows",
        title: "Utilisation de Hyper-V Windows",
        svg: "/assets/svg/server.svg",
    },
    {
        href: "/cours/ip.html",
        tag: "Cours Network IP",
        title: "IP",
        svg: "/assets/svg/ip.svg",
    },
    {
        href: "/cours/linux/readme.html",
        tag: "Cours OS Linux CMD",
        title: "ReadMe de Linux et ses commandes",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/commands.html",
        tag: "Cours OS Linux CMD",
        title: "Utiliser le terminal sur Linux",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/shell.html",
        tag: "Cours OS Linux CMD",
        title: "Histoire des shells sur Linux (Bash, korne, C shell, ...)",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/file.html",
        tag: "Cours OS Linux CMD",
        title: "Utiliser le terminal sur Linux pour gérer des fichiers",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/bash.html",
        tag: "Cours OS Linux CMD",
        title: "Utiliser le terminal sur Linux pour programmer en bash",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/package.html",
        tag: "Cours OS Linux CMD",
        title: "Utiliser le terminal sur Linux pour gérer les paquets (APT, pacman)",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/ps1.html",
        tag: "Cours OS Linux CMD",
        title: "Customiser le terminal sur Linux",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/motd.html",
        tag: "Cours OS Linux CMD",
        title: "Créez un MOTD pour votre serveur Linux",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/process.html",
        tag: "Cours OS Linux CMD",
        title: "Gestion des processus sur Linux",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/ssh.html",
        tag: "Cours OS Linux CMD",
        title: "Installation et gestion des connexions SSH sur Linux",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/user.html",
        tag: "Cours OS Linux CMD",
        title: "Gestion des utilisateurs sur Linux (password, faillock, useradd, group, sudo ...)",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/network.html",
        tag: "Cours OS Linux CMD",
        title: "Gestion du réseau sur Linux (netstat, ps, UFW, ...)",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/code-server.html",
        tag: "Cours OS Linux CMD",
        title: "Installation de code-server sous apache sur Ubuntu",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/0x0.html",
        tag: "Cours OS Linux CMD",
        title: "Site pour envoyer des logs en ligne",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/httpd-src-build.html",
        tag: "Cours OS Linux CMD",
        title: "Compilation et installation de HTTPD à partir du code source",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/lvm.html",
        tag: "Cours OS Linux CMD",
        title: "Gestion du stockage sur Linux (LVM, partitions, disques, encryption, ...)",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux/shutdown.html",
        tag: "Cours OS Linux CMD",
        title: "Gestion de l'arrêt et du redémarrage sur Linux",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/linux.html",
        tag: "Cours OS Linux CMD",
        title: "Linux et ses commandes",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/cours/lm-studio.html",
        tag: "Cours IA",
        title: "LM studio pour lancer un LLM en local",
        svg: "/assets/svg/ai-ml.svg",
    },
    {
        href: "/cours/network.html",
        tag: "Cours Network",
        title: "Réseau",
        svg: "/assets/svg/network.svg",
    },
    {
        href: "/cours/protocoles.html",
        tag: "Cours Network OS",
        title: "Protocoles réseau",
        svg: "/assets/svg/network.svg",
    },
    {
        href: "/cours/powershell.html",
        tag: "Cours CMD OS Windows",
        title: "PowerShell",
        svg: "/assets/svg/languages/powershell.svg",
    },
    {
        href: "/cours/readme.html",
        tag: "ReadMe Cours",
        title: "Le README des cours",
        svg: "/assets/svg/note.svg",
    },
    {
        href: "/cours/retraite.html",
        tag: "Cours",
        title: "Système de retraite",
        svg: "/assets/svg/old-man.svg",
    },
    {
        href: "/cours/sql.html",
        tag: "Cours Web",
        title: "SQL",
        svg: "/assets/svg/languages/sql.svg",
    },
    {
        href: "/cours/web.html",
        tag: "Cours Web",
        title: "Développement web (HTML, CSS, JS, SQL)",
        svg: "/assets/svg/languages/html.svg",
    },
    {
        href: "/cours/Windows.html",
        tag: "Cours Windows CMD OS",
        title: "Windows et ses commandes et astuces",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "https://discord.com/developers",
        tag: "URL .gg Discord",
        title: "Portail développeur Discord",
        svg: "/assets/svg/link.svg",
    },
    {
        href: "https://www.calculator.net/ip-subnet-calculator.html",
        tag: "URL Outils Network IP",
        title: "IP subnet calculator",
        svg: "/assets/svg/link.svg",
    },
    {
        href: "https://www.discordicon.com",
        tag: "URL .gg Discord",
        title: "Créateur de badge Discord",
        svg: "/assets/svg/link.svg",
    },
    {
        href: "https://rebane2001.com/discord-colored-text-generator",
        tag: "URL .gg Discord",
        title: "Générateur de text en couleur Discord",
        svg: "/assets/svg/link.svg",
    },
    {
        href: "/cours/active-directory-approbation.html",
        tag: "Cours Windows",
        title: "Relations d'approbations avec l'Active Directory",
        svg: "/assets/svg/network.svg",
    },
    {
        href: "/cours/gpo.html",
        tag: "Cours Windows",
        title: "GPO Active Directory",
        svg: "/assets/svg/developpement.svg",
    },
    {
        href: "/cours/docker.html",
        tag: "Cours OS",
        title: "Docker",
        svg: "/assets/svg/trademark/docker-16.svg",
    },
    {
        href: "/cours/cisco.html",
        tag: "Cours Network",
        title: "Cisco",
        svg: "/assets/svg/trademark/cisco.svg",
    },
    {
        href: "/cours/reverse-shell.html",
        tag: "Cours URL OS OpSec Outils CMD Windows Linux Network",
        title: "Reverse Shell",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/sitemap.xml",
        tag: "URL XML",
        title: "Sitemap",
        svg: "/assets/svg/network.svg",
    },
    {
        href: "vscode://",
        tag: "URL Developpement Admin ://",
        title: "VSCode ://",
        svg: "/assets/svg/link.svg",
    },
    {
        href: "https://code.visualstudio.com/",
        tag: "URL",
        title: "VSCode download",
        svg: "/assets/svg/download.svg",
    },
    {
        href: "https://vscode.dev/",
        tag: "URL",
        title: "VSCode .dev",
        svg: "/assets/svg/menu.svg",
    },
    {
        href: "https://github.dev/github/dev",
        tag: "URL",
        title: "Github.dev",
        svg: "/assets/svg/menu.svg",
    },
    {
        href: "https://github.com/github/dev",
        tag: "URL",
        title: "Github.dev",
        svg: "/assets/svg/menu.svg",
    },
    {
        href: "github-windows://",
        tag: "URL Developpement Github ://",
        title: "Github Windows ://",
        svg: "/assets/svg/link.svg",
    },
    {
        href: "https://desktop.github.com/",
        tag: "URL Github",
        title: "Github Windows download",
        svg: "/assets/svg/download.svg",
    },
    {
        href: "https://github.com/",
        tag: "Queryable URL Github Web",
        queryURL: "https://github.com/search?q=",
        title: "Github",
        svg: "/assets/svg/trademark/github.svg",
    },
    {
        href: "https://git-scm.com/",
        tag: "URL Github",
        title: "Git",
        svg: "/assets/svg/trademark/git.svg",
    },
    {
        href: "https://github.com/git-for-windows/git/releases/latest",
        tag: "URL Github",
        title: "Git latest releases",
        svg: "/assets/svg/trademark/git.svg",
    },
    {
        href: "https://developer.mozilla.org/",
        tag: "URL",
        title: "MSDN",
        svg: "/assets/svg/language.svg",
    },
    {
        href: "https://www.svgrepo.com/",
        tag: "Queryable URL Outils Web",
        title: "SVGRepo",
        queryURL: "https://www.svgrepo.com/vectors/",
        svg: "/assets/svg/svg.svg",
    },
    {
        href: "https://explainshell.com/",
        tag: "URL CMD OS",
        title: "explain shell",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "/github/readme.html#Repo",
        tag: "URL Github ReadMe",
        title: "Github ReadMe #Repo",
        svg: "/assets/svg/language.svg",
    },
    {
        href: "calculator://",
        tag: "URL :// Outils",
        title: "Calculatrice ://",
        svg: "/assets/svg/link.svg",
    },
    {
        href: "https://fr.wikipedia.org/wiki/Schéma_d'URI",
        tag: "URL Cours Web ://",
        title: "Wikipedia.org Schéma d'URI",
        svg: "/assets/svg/link.svg",
    },
    {
        href: "/outils/logger.html",
        svg: "/assets/svg/ip.svg",
        tag: "OpSec Outils Network IP Web",
        title: "Outils IP & UserAgent",
    },
    {
        href: "https://openvpn.net/",
        svg: "/assets/svg/network.svg",
        tag: "URL OpSec",
        title: "OpenVPN",
    },
    {
        href: "https://mullvad.net/",
        svg: "/assets/svg/network.svg",
        tag: "URL OpSec",
        title: "Mullvad",
    },
    {
        href: "https://keepassxc.org/",
        svg: "/assets/svg/password.svg",
        tag: "URL OpSec",
        title: "KeePassXC",
    },
    {
        href: "https://github.com/keepassxreboot/keepassxc",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "URL OpSec Github",
        title: "KeePassXC Repo",
    },
    {
        href: "https://github.com/keeweb/keeweb",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "URL OpSec Github",
        title: "KeeWeb Repo",
    },
    {
        href: "https://app.keeweb.info/",
        svg: "/assets/svg/password.svg",
        tag: "URL OpSec",
        title: "App.KeeWeb.info",
    },
    {
        href: "https://github.com/Kunzisoft/KeePassDX",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "URL OpSec",
        title: "KeePassDX Repo",
    },
    {
        href: "https://play.google.com/store/apps/details?id=com.kunzisoft.keepass.free",
        svg: "/assets/svg/trademark/google-play.svg",
        tag: "URL OpSec Google",
        title: "KeePassDX Android",
    },
    {
        href: "https://www.keepassdx.com/",
        svg: "/assets/svg/password.svg",
        tag: "URL OpSec",
        title: "KeePassDX.com",
    },
    {
        href: "https://www.motdepasse.xyz/",
        svg: "/assets/svg/password.svg",
        tag: "URL OpSec",
        title: "motdepasse .xyz",
    },
    {
        href: "https://veracrypt.fr/",
        svg: "/assets/svg/password.svg",
        tag: "URL OpSec OS",
        title: "VeraCrypt",
    },
    {
        href: "https://www.virustotal.com/",
        svg: "/assets/svg/virus.svg",
        tag: "URL OpSec",
        title: "VirusTotal",
    },
    {
        href: "https://www.torproject.org/",
        svg: "/assets/svg/trademark/tor.svg",
        tag: "URL OpSec",
        title: "Tor",
    },
    {
        href: "https://tails.net/",
        svg: "/assets/svg/trademark/tails.svg",
        tag: "URL OpSec OS Linux",
        title: "Tails",
    },
    {
        href: "https://gnupg.org/",
        svg: "/assets/svg/contact.svg",
        tag: "URL OpSec",
        title: "GnuPG",
    },
    {
        href: "https://pgp.mit.edu/",
        svg: "/assets/svg/verify.svg",
        tag: "URL OpSec",
        title: "PGP MIT",
    },
    {
        href: "https://www.thunderbird.net/",
        svg: "/assets/svg/mail.svg",
        tag: "URL OpSec",
        title: "Thunderbird",
    },
    {
        href: "https://signal.org/",
        svg: "/assets/svg/contact.svg",
        tag: "URL OpSec",
        title: "Signal",
    },
    {
        href: "https://www.getmonero.org/",
        svg: "/assets/svg/xmr.svg",
        tag: "URL OpSec Crypto",
        title: "Monero",
    },
    {
        href: "https://www.wireshark.org/",
        svg: "/assets/svg/network.svg",
        tag: "URL Network OpSec",
        title: "Wireshark",
    },
    {
        href: "https://npcap.com/",
        svg: "/assets/svg/network.svg",
        tag: "URL Network OpSec",
        title: "Npcap",
    },
    {
        href: "/src/js/content/rss.js",
        svg: "/assets/svg/languages/js.svg",
        tag: "RSS URL",
        title: "RSS .JS",
    },
    {
        href: "https://www.toptal.com/developers/keycode",
        svg: "/assets/svg/languages/js.svg",
        tag: "URL Outils Web",
        title: "JavaScript Keyboard code",
    },
    {
        href: "https://virtualbox.org",
        svg: "/assets/svg/network.svg",
        tag: "URL Linux Outils",
        title: "VirtualBox",
    },
    {
        href: "https://proxmox.com",
        svg: "/assets/svg/network.svg",
        tag: "URL Linux Outils",
        title: "ProxMox",
    },
    {
        href: "https://learn.microsoft.com/fr-fr/sysinternals/",
        svg: "/assets/svg/tools.svg",
        tag: "Windows URL Outils",
        title: "Microsoft SysInternals",
    },
    {
        href: "https://learn.microsoft.com/fr-fr/sysinternals/downloads/bginfo",
        svg: "/assets/svg/tools.svg",
        tag: "Windows URL Outils",
        title: "BGInfo SysInternals",
    },
    {
        href: "https://live.sysinternals.com/",
        svg: "/assets/svg/tools.svg",
        tag: "Windows URL Outils",
        title: "Live.SysInternals.com",
    },
    {
        href: "https://haveibeenpwned.com/",
        svg: "/assets/svg/password.svg",
        tag: "URL OpSec Outils",
        title: "have i been pwned?",
    },
    {
        href: "https://openjdk.org/",
        svg: "/assets/svg/languages/java.svg",
        tag: "URL Outils OS Développement",
        title: "openjdk.org (Java)",
    },
    {
        href: "https://learn.microsoft.com/fr-fr/java/",
        svg: "/assets/svg/languages/java.svg",
        tag: "URL Outils OS Développement",
        title: "learn.microsoft.com /java",
    },
    {
        href: "https://learn.microsoft.com/fr-fr/java/openjdk",
        svg: "/assets/svg/languages/java.svg",
        tag: "URL Outils OS Développement",
        title: "learn.microsoft.com /java /openjdk",
    },
    {
        href: "https://learn.microsoft.com/fr-fr/java/openjdk/download",
        svg: "/assets/svg/download.svg",
        tag: "URL Outils OS Développement",
        title: "learn.microsoft.com /java /openjdk /download",
    },
    {
        href: "https://aka.ms/download-jdk/microsoft-jdk-21.0.6-windows-x64.msi",
        svg: "/assets/svg/download.svg",
        tag: "URL Outils OS Développement",
        title: "microsoft-jdk-21.0.6-windows-x64.msi (OpenJDK Java)",
    },
    {
        href: "https://portswigger.net/burp",
        svg: "/assets/svg/network.svg",
        tag: "URL OpSec Web",
        title: "Burp Suite",
    },
    {
        href: "https://portswigger.net/burp/documentation/desktop/getting-started/download-and-install",
        svg: "/assets/svg/network.svg",
        tag: "URL OpSec Web",
        title: "Download Burp Suite",
    },
    {
        href: "https://portswigger.net/burp/vulnerability-scanner",
        svg: "/assets/svg/network.svg",
        tag: "URL OpSec Web",
        title: "Burp Suite vulnerability scanner",
    },
    {
        href: "https://github.com/centreon/centreon",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "Repo Github OS URL",
        title: "Repo Github Centreon",
    },
    {
        href: "https://www.centreon.com/",
        svg: "/assets/svg/link.svg",
        tag: "URL Outils OS Web",
        title: "Centreon.com",
    },
    {
        href: "https://dotnet.microsoft.com/download/dotnet/",
        title: "DotNet Download",
        tag: "URL OS Windows",
        svg: "/assets/svg/link.svg",
    },
    {
        href: "https://github.com/windirstat/windirstat",
        svg: "/assets/svg/trademark/windows.svg",
        tag: "URL Repo OS Windows Outils",
        title: "Win Dir Stat Github Repo",
    },
    {
        href: "https://windirstat.net/",
        svg: "/assets/svg/link.svg",
        tag: "URL OS Outils Windows",
        title: "Win Dir Stat",
    },
    {
        href: "https://minesweeper.online/help/patterns",
        svg: "/assets/svg/link.svg",
        tag: "Jeux Outils Cours URL",
        title: "MineSweeper / Démineur - Patterns",
    },
    {
        href: "/outils/crashmybrowser",
        svg: "/assets/svg/languages/html.svg",
        tag: "Web Outils URL",
        title: "Crash Memory & CPU grinder",
    },
    {
        href: "https://discord.com/developers/active-developer",
        svg: "/assets/svg/trademark/discord.svg",
        tag: ".gg Discord Outils URL Développement",
        title: "Active Developer Badge",
    },
    {
        href: "https://discord.com/developers/applications",
        svg: "/assets/svg/trademark/discord.svg",
        tag: ".gg Discord Outils URL Développement",
        title: "Discord Developer Apps",
    },
    {
        href: "/outils/rsa.html",
        svg: "/assets/svg/password.svg",
        tag: "Outils OpSec",
        title: "Chiffrement RSA",
    },
    {
        href: "https://steamdb.info/",
        svg: "/assets/svg/trademark/steam.svg",
        tag: "URL Outils Jeux",
        title: "Steamdb",
    },
    {
        href: "https://store.steampowered.com/stats/content/",
        svg: "/assets/svg/trademark/steam.svg",
        tag: "URL Outils Jeux",
        title: "Statistiques de téléchargement Steam & carte",
    },
    {
        href: "https://steamladder.com/",
        svg: "/assets/svg/trademark/steam.svg",
        tag: "URL Outils Jeux",
        title: "Steamladder",
    },
    {
        href: "https://grapheneos.org/",
        svg: "/assets/svg/.svg",
        tag: "URL Outils OpSec OS",
        title: "GrapheneOS",
    },
    {
        href: "https://github.com/GrapheneOS",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "Repo Github OS OpSec Outils",
        title: "Repo GrapheneOS",
    },
    {
        href: "https://atlasos.net/",
        svg: "/assets/svg/trademark/windows.svg",
        tag: "URL Outils OpSec OS Windows",
        title: "Atlas OS",
    },
    {
        href: "https://github.com/Atlas-OS/Atlas",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "Repo Github OS OpSec Outils Windows",
        title: "Repo Atlas OS",
    },
    {
        href: "https://www.ntlite.com/",
        svg: "/assets/svg/trademark/windows.svg",
        tag: "URL OS Windows",
        title: "NTLite",
    },
    {
        href: "https://github.com/hectorm/hblock",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "Repo Github OpSec Web",
        title: "Repo hBlock",
    },
    {
        href: "https://hblock.molinero.dev/",
        svg: "/assets/svg/network.svg",
        tag: "URL OpSec Web",
        title: "hBlock",
    },
    {
        href: "https://archlinux.org/",
        svg: "/assets/svg/linux.svg",
        tag: "OS Linux URL",
        title: "ArchLinux",
    },
    {
        href: "https://wiki.archlinux.org/",
        svg: "/assets/svg/book.svg",
        tag: "OS Linux URL Développement ReadMe Cours",
        title: "Wiki ArchLinux",
    },
    {
        href: "https://github.com/archlinux",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "Repo Github OS Linux",
        title: "Repo ArchLinux",
    },
    {
        href: "https://archlinux.org/download/",
        svg: "/assets/svg/download.svg",
        tag: "OS Linux URL ",
        title: "Download ArchLinux",
    },
    {
        href: "https://github.com/Altherneum/.github/blob/main/note/OS/Linux/Arch/",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "Repo Github Linux OS Outils URL",
        title: ".github Arch",
    },
    {
        href: "https://raw.githubusercontent.com/Altherneum/.github/refs/heads/main/note/OS/Linux/Arch/Archterneum/install.sh",
        svg: "/assets/svg/link.svg",
        tag: "Repo Github Linux OS Outils URL",
        title: "arch.sh auto install",
    },
    {
        href: "https://guacamole.apache.org/",
        svg: "/assets/svg/trademark/apache.svg",
        tag: "URL OS Outils Web Linux Network",
        title: "Apache Guacamole",
    },
    {
        href: "https://etcher.balena.io/",
        svg: "/assets/svg/usb-flash-drive.svg",
        tag: "URL OS Outils",
        title: "Balena Etcher",
    },
    {
        href: "https://rufus.ie/",
        svg: "/assets/svg/usb-flash-drive.svg",
        tag: "URL OS Outils",
        title: "Rufus",
    },
    {
        href: "https://drive.google.com/",
        svg: "/assets/svg/trademark/google-drive.svg",
        tag: "URL OS Outils Web Windows Google Queryable",
        queryURL: "https://drive.google.com/drive/search?q=",
        title: "Google Drive",
    },
    {
        href: "https://dl.google.com/drive-file-stream/GoogleDriveSetup.exe",
        svg: "/assets/svg/trademark/google-drive.svg",
        tag: "URL OS Outils Web Windows Google",
        title: "Google Drive Setup",
    },
    {
        href: "https://web.archive.org/",
        svg: "/assets/svg/download.svg",
        tag: "URL OS Outils Web",
        title: "Wayback Machine",
    },
    {
        href: "https://drivenlisten.com/",
        svg: "/assets/svg/link.svg",
        tag: "URL Outils Web",
        title: "Drive & Listen",
    },
    {
        href: "https://www.shodan.io/",
        svg: "/assets/svg/link.svg",
        tag: "URL Outils Web OpSec",
        title: "Shodan .io",
    },
    {
        href: "https://www.microsoft.com/fr-fr/software-download/windows11",
        svg: "/assets/svg/download.svg",
        tag: "URL OS Outils Web Windows",
        title: "Télécharger Windows 11 (ISO/Setup)"
    },
    {
        href: "https://www.chiark.greenend.org.uk/~sgtatham/putty/",
        svg: "/assets/svg/console.svg",
        tag: "URL Outils OS OpSec CMD Web Développement Windows Linux",
        title: "PuTTY",
    },
    {
        href: "https://www.chiark.greenend.org.uk/~sgtatham/putty/latest",
        svg: "/assets/svg/download.svg",
        tag: "URL Outils OS OpSec CMD Web Développement Windows Linux",
        title: "PuTTY latest",
    },
    {
        href: "https://filezilla-project.org/",
        svg: "/assets/svg/ftp.svg",
        tag: "URL Outils OS OpSec CMD Web Développement Windows Linux",
        title: "FileZila",
    },
    {
        href: "https://filezilla-project.org/download.php?platform=win64",
        svg: "/assets/svg/download.svg",
        tag: "URL Outils OS OpSec CMD Web Développement Windows Linux",
        title: "FileZila latest",
    },
    {
        href: "https://github.com/ShareX/ShareX/releases/latest",
        svg: "/assets/svg/download.svg",
        tag: "URL Outils OS Web Windows",
        title: "ShareX (ScreenShot)",
    },
    {
        href: "https://www.amd.com/fr/support/download/drivers.html",
        svg: "/assets/svg/download.svg",
        tag: "URL Outils Jeux OS Web Windows Linux",
        title: "AMD Driver (GPU)",
    },
    {
        href: "https://github.com/Altherneum/.github/blob/main/note/OS/Windows/GPU_config.xml",
        svg: "/assets/svg/download.svg",
        tag: "URL Outils Jeux OS Web Windows Linux Admin",
        title: "AMD Config (GPU)",
    },
    {
        href: "https://discord.com/api/downloads/distributions/app/installers/latest?channel=stable&platform=win&arch=x64",
        svg: "/assets/svg/download.svg",
        tag: ".gg Discord Outils URL Windows",
        title: "Discord Setup",
    },
    {
        href: "https://vencord.dev/",
        svg: "/assets/svg/link.svg",
        tag: ".gg Discord Outils URL Développement",
        title: "Vencord",
    },
    {
        href: "https://github.com/Vencord/Installer/releases/latest/download/VencordInstaller.exe",
        svg: "/assets/svg/download.svg",
        tag: ".gg Discord Outils URL Développement Windows",
        title: "Vencord Installer latest release",
    },
    {
        href: "/outils/donut.html",
        svg: "/assets/svg/link.svg",
        tag: "URL Admin Cours ReadMe Outils",
        title: "Un donut en 3D 🍩",
    },
    {
        href: "https://messages.google.com/",
        title: "Google SMS",
        tag: "Google URL Web Outils",
        svg: "/assets/svg/contact.svg",
    },
    {
        href: "https://messages.google.com/web",
        title: "Google SMS Web",
        tag: "Google URL Web Outils",
        svg: "/assets/svg/contact.svg",
    },
    {
        href: "https://www.google.fr/search",
        title: "Rechercher sur Google",
        tag: "Google URL Web Outils Queryable",
        queryURL: "https://www.google.fr/search?q=",
        svg: "/assets/svg/loading.svg",
    },
    {
        href: "https://translate.google.fr/",
        title: "Traduction vers l'Anglais",
        tag: "Google URL Web Outils Queryable",
        queryURL: "https://translate.google.fr/?sl=auto&tl=en&op=translate&text=",
        svg: "/assets/svg/langue.svg",
    },
    {
        href: "https://translate.google.fr/",
        title: "Traduction vers le Français",
        tag: "Google URL Web Outils Queryable",
        queryURL: "https://translate.google.fr/?sl=auto&tl=fr&op=translate&text=",
        svg: "/assets/svg/langue.svg",
    },
    {
        href: "https://maps.google.fr/",
        title: "Google map",
        tag: "Google URL Web Outils Queryable",
        queryURL: "https://www.google.fr/maps/search/",
        svg: "/assets/svg/map-pin.svg",
    },
    {
        href: "https://keep.google.com/",
        title: "Goole notes",
        tag: "Google URL Web Outils Queryable",
        queryURL: "https://keep.google.com/#search/text%253D",
        svg: "/assets/svg/note.svg",
    },
    {
        href: "https://mail.google.com/",
        title: "GMail",
        tag: "Google URL Web Outils Queryable",
        queryURL: "https://mail.google.com/mail/#search/",
        svg: "/assets/svg/mail.svg",
    },
    {
        href: "https://www.google.com/chrome/",
        title: "Télécharger Google Chrome",
        tag: "Google URL Web Outils OS Windows",
        svg: "/assets/svg/download.svg",
    },
    {
        href: "https://console.cloud.google.com/vertex-ai/studio/multimodal",
        title: "Google Cloud Console",
        tag: "Google URL Web Outils",
        svg: "/assets/svg/console.svg",
    },
    {
        href: "https://myaccount.google.com/",
        title: "Google My Account",
        tag: "Google URL Web Outils OpSec",
        svg: "/assets/svg/password.svg",
    },
    {
        href: "https://calendar.google.com/",
        title: "Calendrier Google",
        tag: "Google URL Web Outils",
        svg: "/assets/svg/book.svg",
    },
    {
        href: "https://contacts.google.com/",
        title: "Google Contacts",
        tag: "Google URL Web Outils Queryable",
        queryURL: "https://contacts.google.com/search/",
        svg: "/assets/svg/people.svg",
    },
    {
        href: "https://youtube.com/",
        title: "YouTube",
        tag: "Google Queryable URL Web Outils",
        queryURL: "https://www.youtube.com/results?search_query=",
        svg: "/assets/svg/trademark/youtube.svg"
    },
    {
        href: "https://trends.google.fr/",
        title: "Google Trends",
        tag: "Google Queryable URL Web Outils",
        queryURL: "https://trends.google.fr/trends/explore?q=",
        svg: "/assets/svg/chart-column.svg"
    },
    {
        href: "https://keep.google.com/",
        title: "Google Notes",
        tag: "Google Queryable URL Web Outils",
        queryURL: "https://keep.google.com/u/1/#search/text/",
        svg: "/assets/svg/book.svg"
    },
    {
        href: "https://tasks.google.com/",
        title: "Google Task",
        tag: "Google URL Web Outils",
        svg: "/assets/svg/book.svg"
    },
    {
        href: "https://docs.google.com/videos/u/0/",
        title: "Google Vids (capture et enregistrement d'écran)",
        tag: "Google URL Web Outils",
        svg: "/assets/svg/book.svg"
    },
    {
        href: "https://notebook.google.com/notebook/",
        title: "Google NoteBook",
        tag: "Google URL Web Outils",
        svg: "/assets/svg/book.svg"
    },
    {
        href: "https://photos.google.com/",
        title: "Google Photos",
        tag: "Google URL Web Outils",
        svg: "/assets/svg/book.svg"
    },
    {
        href: "https://docs.google.com/forms/",
        title: "Google Forms",
        tag: "Google URL Web Outils",
        svg: "/assets/svg/book.svg"
    },
    {
        href: "https://www.google.com/android/find/",
        title: "Google Android Find (Localiser)",
        tag: "Google URL Web Outils",
        svg: "/assets/svg/book.svg"
    },
    {
        href: "https://fonts.google.com",
        title: "Google Fonts",
        tag: "Google URL Web Outils",
        svg: "/assets/svg/book.svg"
    },
    {
        href: "https://gemini.google.com/app",
        title: "Google Gemini (AI)",
        tag: "Google URL Web Outils IA",
        svg: "/assets/svg/book.svg"
    },
    {
        href: "https://news.google.com/",
        title: "Google Actualités",
        tag: "Google Queryable URL Web Outils",
        queryURL: "https://news.google.com/search?q=",
        svg: "/assets/svg/new.svg"
    },
    {
        href: "https://www.google.com/alerts",
        title: "Google Alertes",
        tag: "Google URL Web Outils OpSec",
        svg: "/assets/svg/warning.svg"
    },
    {
        href: "https://doc.altherneum.fr",
        title: "Doc.Altherneum",
        tag: "URL Queryable",
        svg: "/assets/svg/home.svg",
        queryURL: "https://doc.altherneum.fr/?search=",
    },
    {
        href: "https://www.geolocation.com/",
        title: "GeoLocation IP",
        tag: "URL Queryable outils web OpSec IP Network",
        svg: "/assets/svg/ip.svg",
        queryURL: "https://www.geolocation.com/fr/index?ip=",
    },
    {
        href: "https://dnschecker.org/",
        title: "DNS checker CNAME ➡️ A",
        tag: "URL Queryable outils web OpSec IP Network",
        svg: "/assets/svg/ip.svg",
        queryURL: "https://dnschecker.org/#A/",
    },
    {
        href: "https://dnschecker.org/",
        title: "DNS checker CNAME ➡️ CNAME",
        tag: "URL Queryable outils web OpSec IP Network",
        svg: "/assets/svg/ip.svg",
        queryURL: "https://dnschecker.org/#CNAME/",
    },
    {
        href: "https://dnschecker.org/",
        title: "DNS checker SRV ➡️ CNAME:Port",
        tag: "URL Queryable outils web OpSec IP Network",
        svg: "/assets/svg/ip.svg",
        queryURL: "https://dnschecker.org/#SRV/",
    },
    {
        href: "https://www.imdb.com/",
        title: "IMDB Internet Movie DataBase",
        tag: "URL Web outils Queryable Film",
        svg: "/assets/svg/film.svg",
        queryURL: "https://www.imdb.com/fr/find/?q=",
    },
    {
        href: "https://fr.wikipedia.org/",
        title: "Wikipédia",
        tag: "URL Web outils Queryable",
        svg: "/assets/svg/book.svg",
        queryURL: "https://fr.wikipedia.org/wiki/",
    },
    {
        href: "https://chat.mistral.ai/chat",
        title: "Mistral AI chat",
        tag: "URL Web outils IA",
        svg: "/assets/svg/ai-ml.svg",
    },
    {
        href: "https://code.altherneum.fr/",
        title: "Code-Server @ Altherneum .fr",
        tag: "URL :// Outils Github Admin Développement Queryable",
        svg: "/assets/svg/language.svg",
        queryURL: "https://code.altherneum.fr/?folder=",
    },
    {
        href: "https://code.altherneum.fr/?folder=/home/vscode/repo/",
        title: "Code-Server ~/repo /...",
        tag: "URL :// Outils Github Admin Développement Queryable",
        svg: "/assets/svg/language.svg",
        queryURL: "https://code.altherneum.fr/?folder=/home/vscode/repo/",
    },
    {
        href: "https://3000.code.altherneum.fr/",
        title: "Live Preview - Code-Server @ Altherneum .fr",
        tag: "URL :// Outils Github Admin Développement Queryable",
        svg: "/assets/svg/language.svg",
        queryURL: "https://3000.code.altherneum.fr/",
    },
    {
        href: "https://ipinfo.io/",
        title: "ipinfo.io",
        tag: "IP Queryable URL Outils OpSec Web",
        svg: "/assets/svg/ip.svg",
        queryURL: "https://ipinfo.io/",
    },
    {
        href: "https://quickref.me/",
        title: "quickref.me",
        tag: "Queryable URL Outils Admin Web Cours Développement",
        svg: "/assets/svg/book.svg",
        queryURL: "https://quickref.me/",
    },
    {
        href: "/outils/frames",
        title: "Frames animés",
        tag: "URL Outils Admin Web Cours Développement",
        svg: "/assets/svg/book.svg",
    },
    {
        href: "https://systeminformer.sourceforge.io/",
        svg: "/assets/svg/link.svg",
        tag: "OS Windows OpSec",
        title: "System Informer",
    },
    {
        href: "https://sourceforge.net/projects/processhacker/",
        svg: "/assets/svg/link.svg",
        tag: "OS Windows OpSec",
        title: "Process hacker",
    },
    {
        href: "https://winaero.com/",
        svg: "/assets/svg/link.svg",
        tag: "OS Windows OpSec",
        title: "WinAero",
    },
    {
        href: "https://regexr.com/",
        svg: "/assets/svg/link.svg",
        tag: "Outils Web Développement URL",
        title: "Regular expression",
    },
    {
        href: "https://regex101.com/",
        svg: "/assets/svg/link.svg",
        tag: "Outils Web Développement URL",
        title: "Regular expression",
    },
    {
        href: "https://sed.js.org/",
        svg: "/assets/svg/link.svg",
        tag: "Outils Web Développement URL",
        title: "GNU sed REPL (Regex)",
    },
    {
        href: "https://usebottles.com/",
        svg: "/assets/svg/link.svg",
        tag: "Linux OS Outils Jeux Windows",
        title: "Run Windows in a Bottle",
    },
    {
        href: "https://www.nerdfonts.com/cheat-sheet",
        svg: "/assets/svg/link.svg",
        tag: "Linux OS Outils Web Développement Windows",
        title: "Nerd Fonts",
    },
    {
        href: "https://bash-prompt-generator.org/",
        svg: "/assets/svg/console.svg",
        tag: "Linux OS Outils CMD",
        title: "Bash prompt generator",
    },
    {
        href: "https://www.data.gouv.fr/",
        svg: "/assets/svg/flag-fr.svg",
        tag: "URL Outils Web Network",
        title: "Data Gouv FR",
    },
    {
        href: "https://filigrane.beta.gouv.fr/",
        svg: "/assets/svg/flag-fr.svg",
        tag: "URL Outils Web OpSec",
        title: "Filigrane Beta Gouv FR",
    },
    {
        href: "https://secnumacademie.gouv.fr/",
        svg: "/assets/svg/flag-fr.svg",
        tag: "URL Outils Web OpSec",
        title: "Sec Num Academie Gouv FR",
    },
    {
        href: "https://keybase.io/",
        svg: "/assets/svg/security.svg",
        tag: "URL Outils Web Admin",
        title: "KeyBase .io",
    },
    {
        href: "https://trendstimecapsule.ue.r.appspot.com",
        svg: "/assets/svg/link.svg",
        tag: "URL Web",
        title: "Trends time capsule",
    },
    {
        href: "https://www.w3schools.com/",
        svg: "/assets/svg/link.svg",
        tag: "URL Outils Web Développement",
        title: "W3Schools",
    },
    {
        href: "https://hits.dwyl.com/",
        svg: "/assets/svg/link.svg",
        tag: "Outils URL Web Développement",
        title: "Hits dwyl view counter",
    },
    {
        href: "https://cloud.google.com/shell",
        svg: "/assets/svg/console.svg",
        tag: "URL Web Outils OS",
        title: "Google cloud shell",
    },
    {
        href: "https://www.odoo.com",
        svg: "/assets/svg/link.svg",
        tag: "URL Web",
        title: "Odoo",
    },
    {
        href: "https://github.com/gorhill/uBlock",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "Outils URL Repo Web",
        title: "uBlock Repo",
    },
    {
        href: "https://nmap.org/",
        svg: "/assets/svg/security.svg",
        tag: "Outils URL OpSec Network OS",
        title: "NMap",
    },
    {
        href: "https://www.myinstants.com/fr/index/fr/",
        svg: "/assets/svg/music.svg",
        tag: "URL Outils Web",
        title: "MyInstants SoundBoard",
    },
    {
        href: "https://pastebin.com/",
        svg: "/assets/svg/link.svg",
        tag: "URL Outils Web Admin",
        title: "PasteBin",
    },
    {
        href: "https://docs.github.com/fr/codespaces",
        svg: "/assets/svg/trademark/vscode.svg",
        tag: "URL Cours Github",
        title: "Github CodeSpace Docs",
    },
    {
        href: "https://code.visualstudio.com/docs/remote/codespaces",
        svg: "/assets/svg/trademark/vscode.svg",
        tag: "URL Cours Github",
        title: "VisualStudio CodeSpace Docs",
    },
    {
        href: "https://mxtoolbox.com/",
        svg: "/assets/svg/link.svg",
        tag: "Outils URL Web Admin Network",
        title: "MXToolBox",
    },
    {
        href: "https://github.com//Altherneum/.github/tree/main/note/RTFM/v1.pdf",
        svg: "/assets/svg/languages/pdf.svg",
        tag: "Outils URL Admin",
        title: "RTFM",
    },
    {
        href: "https://github.com//Altherneum/.github/tree/main/note/RTFM/v1.1.pdf",
        svg: "/assets/svg/languages/pdf.svg",
        tag: "Outils URL Admin",
        title: "RTFM V1.1",
    },
    {
        href: "https://aircrack-ng.org/",
        svg: "/assets/svg/security.svg",
        tag: "URL Outils OpSec OS Network",
        title: "AirCrack NG",
    },
    {
        href: "https://uptime.kuma.pet/",
        svg: "/assets/svg/chart-column.svg",
        tag: "URL Outils OS",
        title: "Uptime Kuma",
    },
    {
        href: "https://github.com/louislam/uptime-kuma",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "URL Outils Repo OS",
        title: "Uptime Kuma Repo",
    },
    {
        href: "https://upptime.js.org/",
        svg: "/assets/svg/chart-column.svg",
        tag: "URL Outils OS",
        title: "UptimeJS",
    },
    {
        href: "https://github.com/upptime/upptime",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "URL Outils Repo OS",
        title: "UptimeJS Repo",
    },
    {
        href: "https://containrrr.dev/watchtower/",
        svg: "/assets/svg/tools.svg",
        tag: "URL Linux Outils OS",
        title: "WatchTower",
    },
    {
        href: "https://github.com/containrrr/watchtower",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "URL Linux Outils OS Repo",
        title: "WatchTower Repo",
    },
    {
        href: "https://github.com/gibbed/SteamAchievementManager",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "URL Jeux Repo",
        title: "Steam Achievement Manager",
    },
    {
        href: "https://github.com/Triky313/AlbionOnline-StatisticsAnalysis",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "URL Jeux Repo",
        title: "AlbionOnline Statistics Analysis Repo",
    },
    {
        href: "https://github.com/Zeldruck/Albion-Online-ZQRadar",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "URL Jeux Repo",
        title: "ZQRadar Repo",
    },
    {
        href: "https://meteorclient.com/",
        svg: "/assets/svg/trademark/minecraft.svg",
        tag: "URL Jeux",
        title: "Meteor",
    },
    {
        href: "https://github.com/MeteorDevelopment",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "URL Jeux Repo",
        title: "Meteor Repo",
    },
    {
        href: "https://www.wurstclient.net/",
        svg: "/assets/svg/trademark/minecraft.svg",
        tag: "URL Jeux",
        title: "Wurst",
    },
    {
        href: "https://github.com/Wurst-Imperium/Wurst7",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "URL Jeux Repo",
        title: "Wurst Repo",
    },
    {
        href: "https://gchq.github.io/CyberChef/",
        svg: "/assets/svg/tools.svg",
        tag: "Outils Web URL Admin OpSec",
        title: "Cyber Chef",
    },
    {
        href: "https://keeweb.altherneum.fr/",
        svg: "/assets/svg/password.svg",
        tag: "Outils Web URL Admin OpSec",
        title: "KeeWeb - Web KeePass",
    },
    {
        href: "https://git.altherneum.fr/",
        svg: "/assets/svg/trademark/repo.svg",
        tag: "Outils Web URL Admin OpSec Repo Github",
        title: "Forgejo - Web Git",
    },
];

/*

    {
        href: "",
        svg: "/assets/svg/.svg",
        tag: "",
        title: "",
    },
*/

var tagList = ["IP", "Queryable", "Google", "Cours", "URL", "Network", "Github", "CMD", ".gg", "Discord", "OpSec", "Crypto", "OS", "Outils", "ReadMe", "RSS", "XML", "Windows", "Web", "IA", "Linux", "Repo", "Jeux", "Admin", "Développement", "://", "video", "music", "film", "anime", "serie"];

function getTagList(maxSize){
    var tagListReturned = [];
    if (maxSize >= 1) {
        for (let id = 0; id < maxSize; id++) {
            var random = Math.floor(Math.random() * tagList.length);
            if (!tagListReturned.includes(tagList[random])) {
                tagListReturned.push(tagList[random]);
            }
            else {
                id--;
            }
        }
    }
    else {
        tagListReturned = tagList;
    }
    return tagListReturned;
}
