var filmLinks = [
    {
        "filmID": "tt2084970",
        "category": "film",
        "note": "love",
        "title": "Imitation Game",
        "description": "Pendant la Seconde Guerre mondiale, le génie mathématique anglais Alan Turing essaie de déchiffrer le code allemand Enigma avec l'aide d'autres mathématiciens.",
        "imageURL": "",
    },
    {
        "filmID": "tt0988045",
        "category": "film",
        "note": "best",
        "title": "Sherlock Holmes",
        "description": "Le détective Sherlock Holmes et son fidèle partenaire Watson se lancent dans une lutte contre un ennemi dont le complot constitue une menace pour l'Angleterre.",
        "imageURL": "",
    },
    {
        "filmID": "tt1515091",
        "category": "film",
        "note": "best",
        "title": "Sherlock Holmes: Jeu d'ombres",
        "description": "Sherlock Holmes et son acolyte, le Docteur Watson unissent leurs forces pour déjouer et arrêter leur plus féroce adversaire, le Professeur Moriarty.",
        "imageURL": "",
    },
    {
        "filmID": "tt1241317",
        "category": "film",
        "note": "medium",
        "title": "Death Note",
        "description": "Un lycéen nommé Light Turner découvre un mystérieux carnet de notes qui a le pouvoir de tuer quiconque dont le nom est écrit dans ses pages et lance une croisade secrète pour débarrasser le monde des criminels.",
        "imageURL": "",
    },
    {
        "filmID": "tt9783600",
        "category": "film",
        "note": "best",
        "title": "Spiderhead",
        "description": "Dans un futur proche, les prisonniers se portent volontaires comme cobayes médicaux pour écourter leur peine. Un des cobayes pour un médicament créant des sentiments d'amour commence à remettre en question la réalité de ses émotions.",
        "imageURL": "",
    },
    {
        "filmID": "tt0434409",
        "category": "film",
        "note": "love",
        "title": "V pour vendetta",
        "description": "Dans un futur tyrannique en Grande Bretagne, un défenseur de la liberté ténébreux connu uniquement sous le pseudonyme de \"\"V\"\" complote pour renverser le régime avec l'aide d'une jeune femme.",
        "imageURL": "",
    },
    {
        "filmID": "tt0478087",
        "category": "film",
        "note": "best",
        "title": "Las Vegas 21",
        "description": "Inspiré de faits réels, 21 relate l'histoire de six étudiants du MIT qui ont été formés pour devenir des experts en comptage de cartes et qui se sont ensuite emparés des casinos de Vegas pour gagner des millions.",
        "imageURL": "",
    },
    {
        "filmID": "tt0281364",
        "category": "film",
        "note": "medium",
        "title": "Wasabi",
        "description": "Au Japon lors des funérailles de son amour perdu depuis longtemps, un détective français coriace apprend qu'il a aussi une fille adolescente et que sa vie est en danger à cause des Yakuza.",
        "imageURL": "",
    },
    {
        "filmID": "tt0110413",
        "category": "film",
        "note": "best",
        "title": "Léon",
        "description": "Matilda, une fillette de 12 ans, est prise à contrecoeur sous l'aile de Léon, un assassin professionnel, après le meurtre de sa famille. Léon et Matilda forment une relation peu habituelle, elle devient sa protégée et apprend le métier d'assassin.",
        "imageURL": "",
    },
    {
        "filmID": "tt0109830",
        "category": "film",
        "note": "best",
        "title": "Forrest Gump",
        "description": "Les présidences de Kennedy et Johnson, le Vietnam, le Watergate et d'autres histoires se déroulent à travers la perspective d'un homme d'Alabama avec un QI de 75.",
        "imageURL": "",
    },
    {
        "filmID": "tt15398776",
        "category": "film",
        "note": "best",
        "title": "Oppenheimer",
        "description": "L'histoire du scientifique américain J. Robert Oppenheimer et son rôle dans le développement de la bombe atomique.",
        "imageURL": "",
    },
    {
        "filmID": "tt8323668",
        "category": "film",
        "note": "best",
        "title": "Jerry and Marge Go Large",
        "description": "Basé sur la véritable histoire du couple Jerry et Marge Selbee, qui gagnent à la loterie et utilisent l'argent pour faire revivre leur petite ville.",
        "imageURL": "",
    },
    {
        "filmID": "tt2293138",
        "category": "film",
        "note": "medium",
        "title": "Vive la France",
        "description": "Même si c'est là que fut inventé le taboulé, personne ne connaît le Taboulistan, un minuscule pays d'Asie centrale coincé entre l'Afghanistan, le Kirghizistan et le Tadjikistan. Pour faire connaître son pays sur la scène internationale, Jafaraz Ouèchemagül, le fils du président, invente le ********** publicitaire. Comme première cible, il choisit la tour Eiffel.",
        "imageURL": "",
    },
    {
        "filmID": "tt1677720/",
        "category": "film",
        "note": "medium",
        "title": "Ready Player One",
        "description": "Quand meurt le créateur d'un monde de réalité virtuelle appelé OASIS, ce dernier publie une vidéo dans laquelle il défie tous les utilisateurs d'OASIS de trouver son oeuf de Pâques. Le vainqueur héritera de toute sa fortune.",
        "imageURL": "",
    },
    {
        "filmID": "tt0482571/",
        "category": "film",
        "note": "best",
        "title": "Le Prestige",
        "description": "Après un tragique accident, deux magiciens se lancent dans un combat pour créer l'illusion ultime en sacrifiant tout ce qu'ils ont pour déjouer les tours de l'autre.",
        "imageURL": "",
    },
    {
        "filmID": "tt0213149/",
        "category": "film",
        "note": "best",
        "title": "Pearl Harbor",
        "description": "Un récit de guerre et d'amour mêlé à l'Histoire. Deux amis de toujours et une belle infirmière sont entraînés dans l'horreur d'un infâme dimanche matin en 1941.",
        "imageURL": "",
    },
    {
        "filmID": "tt1670345/",
        "category": "film",
        "note": "best",
        "title": "Insaisissables",
        "description": "Un agent du FBI et une détective d'Interpol poursuivent une équipe d'illusionnistes qui braquent des banques pendant leurs spectacles et distribuent au public l'argent volé.",
        "imageURL": "",
    },
    {
        "filmID": "tt3110958/",
        "category": "film",
        "note": "best",
        "title": "Insaisissables 2",
        "description": "Les quatre cavaliers refont surface et sont recrutés de force par un génie de la technologie pour réaliser leur braquage le plus improbable.",
        "imageURL": "",
    },
    {
        "filmID": "tt0110912/",
        "category": "film",
        "note": "best",
        "title": "Pulp Fiction",
        "description": "Les vies de deux hommes de main, d'un boxeur, de la femme d'un gangster et de deux braqueurs s'entremêlent dans quatre histoires de violence et de rédemption.",
        "imageURL": "",
    },
    {
        "filmID": "tt0137523/",
        "category": "film",
        "note": "best",
        "title": "Fight Club",
        "description": "Un employé de bureau insomniaque et un fabriquant de savons forment un club de combat clandestin qui devient beaucoup plus que ça.",
        "imageURL": "",
    },
    {
        "filmID": "tt2005151/",
        "category": "film",
        "note": "best",
        "title": "War Dogs",
        "description": "Vaguement inspiré de la véritable histoire de David Packouz et Efraim Diveroli, deux jeunes hommes ayant ont remporté un contrat de trois cent millions de dollars par le Pentagone afin d'armer les alliés des États-Unis en Afghanistan.",
        "imageURL": "",
    },
    {
        "filmID": "tt0993846/",
        "category": "film",
        "note": "best",
        "title": "Le Loup de Wall Street",
        "description": "Inspiré de l'histoire vraie de Jordan Belfort, de son ascension au rôle de riche courtier à la belle vie jusqu'à sa chute impliquant crime, corruption et les autorités.",
        "imageURL": "",
    },
    {
        "filmID": "tt0120815/",
        "category": "film",
        "note": "best",
        "title": "Il faut sauver le soldat Ryan",
        "description": "À la suite du débarquement en Normandie, un groupe de soldats américains passe derrière les lignes ennemies pour récupérer un parachutiste dont les frères ont été tués au combat.",
        "imageURL": "",
    },
    {
        "filmID": "tt0259060/",
        "category": "film",
        "note": "medium",
        "title": "La Tour Montparnasse infernale",
        "description": "Eric et Ramzy, laveurs de vitre à la Tour Montparnasse, assistent à une prise d'otage des employés, y compris Marie-Joelle de qui Eric est amoureux.",
        "imageURL": "",
    },
    {
        "filmID": "tt0848228/",
        "category": "film",
        "note": "best",
        "title": "Avengers",
        "description": "Les plus grands héros de la Terre doivent s'unir et apprendre à se battre s'ils veulent empêcher Loki et son armée extraterrestre d'asservir l'humanité tout entière.",
        "imageURL": "",
    },
    {
        "filmID": "tt2911666/",
        "category": "film",
        "note": "best",
        "title": "John Wick",
        "description": "Un ancien tueur à gages sort de sa retraite pour retrouver les gangsters qui ont tué son chien et lui a tout pris.",
        "imageURL": "",
    },
    {
        "filmID": "tt4846340/",
        "category": "film",
        "note": "love",
        "title": "Les Figures de l'ombre",
        "description": "L'histoire d'une équipe de mathématiciennes afro-américaines qui ont joué un rôle essentiel à la NASA au cours des premières années du programme spatial américain.",
        "imageURL": "",
    },
    {
        "filmID": "tt1016150/",
        "category": "film",
        "note": "love",
        "title": "À l'Ouest, rien de nouveau",
        "description": "Les expériences terrifiantes et la détresse d'un jeune soldat allemand sur le front de l'Ouest pendant la Première Guerre mondiale.",
        "imageURL": "",
    },
    {
        "filmID": "tt0371746/",
        "category": "film",
        "note": "best",
        "title": "Iron Man",
        "description": "Après avoir été retenu prisonnier dans une grotte afghane, l'ingénieur milliardaire Tony Stark crée une armure unique pour lutter contre le mal.",
        "imageURL": "",
    },
    {
        "filmID": "tt0325980/",
        "category": "film",
        "note": "best",
        "title": "Pirates des Caraïbes",
        "description": "Le forgeron Will Turner fait équipe avec le pirate excentrique \"Capitaine\" Jack Sparrow pour sauver la fille du gouverneur dont il est amoureux des anciens alliés pirates de Jack, à présent devenus morts-vivants.",
        "imageURL": "",
    },
    {
        "filmID": "tt1431045/",
        "category": "film",
        "note": "best",
        "title": "Deadpool",
        "description": "Un mercenaire bien bavard à l'humour noir est soumis à une expérience qui lui donne des pouvoirs de guérison accélérés et une soif de vengeance.",
        "imageURL": "",
    },
    {
        "filmID": "tt1211837/",
        "category": "film",
        "note": "best",
        "title": "Doctor Strange",
        "description": "Lors d'un voyage de guérison physique et spirituelle, un neurochirurgien sensationnel est entraîné dans le monde des arts mystiques.",
        "imageURL": "",
    },
    {
        "filmID": "tt0800369/",
        "category": "film",
        "note": "best",
        "title": "Thor",
        "description": "Thor, Dieu tout puissant mais arrogant, est exilé d'Asgard et envoyé sur à Midgard sur Terre, où il devient rapidement l'un de leurs meilleurs guerriers.",
        "imageURL": "",
    },
    {
        "filmID": "tt0399295/",
        "category": "film",
        "note": "best",
        "title": "Lord of War",
        "description": "Un trafiquant d'armes est en proie à la moralité de son travail alors qu'il est chassé par un agent d'Interpol.",
        "imageURL": "",
    },
    {
        "filmID": "tt0111161/",
        "category": "film",
        "note": "best",
        "title": "Les Évadés",
        "description": "Le banquier Andy Dufresne est arrêté pour avoir tué sa femme et son amant. Après une dure adaptation, il tente d'améliorer les conditions de la prison et de redonner de l'espoir à ses compagnons.",
        "imageURL": "",
    },
    {
        "filmID": "tt0120689/",
        "category": "film",
        "note": "best",
        "title": "La Ligne verte",
        "description": "La vie des gardes du couloir de la mort est touchée par l'un de leurs détenus: a homme noir accusé de meurtre et de viol d'enfants, doté d'un pouvoir mystérieux.",
        "imageURL": "",
    },
    {
        "filmID": "tt1375666/",
        "category": "film",
        "note": "best",
        "title": "Inception",
        "description": "Un voleur qui s'approprie des secrets d'entreprise à l'aide d'une technique de partage de rêves se voit contraint d'effectuer la tâche inverse : implanter une idée dans l'esprit d'un PDG, pour revoir ses enfants.",
        "imageURL": "",
    },
    {
        "filmID": "tt0068646/",
        "category": "film",
        "note": "best",
        "title": "Le Parrain",
        "description": "Le patriarche vieillissant d'une dynastie de la mafia New Yorkaise passe le flambeau de son empire clandestin à son fils réticent.",
        "imageURL": "",
    },
    {
        "filmID": "tt1285016/",
        "category": "film",
        "note": "best",
        "title": "The Social Network",
        "description": "Mark Zuckerberg, étudiant à Harvard, crée le site de réseau social qui deviendra Facebook, mais il se retrouve poursuivi en justice par deux frères qui l'accusent d'avoir volé leur idée ainsi que par le co-fondateur de Facebook qui fut par la suite évincé de l'entreprise.",
        "imageURL": "",
    },
    {
        "filmID": "tt1790864/",
        "category": "film",
        "note": "medium",
        "title": "Le labyrinthe",
        "description": "Thomas est déposé dans une communauté de garçons après que sa mémoire a été effacée et découvre bientôt qu'ils sont tous pris au piège dans un labyrinthe. Il va devoir unir ses forces à celles de ces compagnons \"Coureurs\" s'il veut tenter de s'échapper.",
        "imageURL": "",
    },
    {
        "filmID": "tt0058461/",
        "category": "film",
        "note": "medium",
        "title": "Pour une poignée de dollars",
        "description": "Un tireur errant et solitaire affronte deux familles rivales dans une ville déchirée par la cupidité, l'orgueil et la vengeance.",
        "imageURL": "",
    },
    {
        "filmID": "tt0208092/",
        "category": "film",
        "note": "best",
        "title": "Snatch : Tu braques ou tu raques",
        "description": "Des promoteurs de boxe sans scrupules, des bookmakers violents, un gangster russe, des voleurs amateurs incompétents et des bijoutiers soi-disant juifs se battent pour traquer un diamant volé à la valeur inestimable.",
        "imageURL": "",
    },
    {
        "filmID": "tt0120737/",
        "category": "film",
        "note": "best",
        "title": "Le Seigneur des anneaux : La Communauté de l'anneau",
        "description": "Un Hobbit du Comté et ses huit compagnons se mettent en route pour détruire le puissant anneau unique et sauver la Terre du Milieu du terrible Sauron.",
        "imageURL": "",
    },
    {
        "filmID": "tt0117333/",
        "category": "film",
        "note": "medium",
        "title": "Phénomène",
        "description": "Un homme ordinaire voit une lumière brillante descendre du ciel et découvre qu'il est devenu super intelligent et doué de télékinésie.",
        "imageURL": "",
    },
    {
        "filmID": "tt0175142/",
        "category": "film",
        "note": "best",
        "title": "Scary Movie",
        "description": "Un an après avoir jeté le corps d'un homme qu'ils ont tué accidentellement, un groupe d'adolescents stupides est harcelé par un tueur en série incompetent.",
        "imageURL": "",
    },
    {
        "filmID": "tt0443453/",
        "category": "film",
        "note": "best",
        "title": "Borat",
        "description": "Le présentateur de tv kazakh, Borat, est envoyé aux USA pour faire un reportage sur le plus grand pays du monde. Suivi par son équipe de documentaire, Borat est de plus intéressé par l'idée de trouver et d'épouser Pamela Anderson.",
        "imageURL": "",
    },
    {
        "filmID": "tt1645170/",
        "category": "film",
        "note": "best",
        "title": "The Dictator",
        "description": "L'histoire héroïque d'un dictateur qui a risqué sa vie afin d'assurer que la démocratie ne viendrait jamais dans le pays qu'il oppressait avec tant d'amour.",
        "imageURL": "",
    },
    {
        "filmID": "tt0264464/",
        "category": "film",
        "note": "best",
        "title": "Arrête-moi si tu peux",
        "description": "Un agent expérimenté du FBI poursuit Frank Abagnale Jr. qui, avant son 19e anniversaire, avait réussi à faire des chèques de plusieurs millions de dollars tout en se faisant passer pour un pilote de la compagnie Pan Am, un médecin et un procureur.",
        "imageURL": "",
    },
    {
        "filmID": "tt0120382/",
        "category": "film",
        "note": "love",
        "title": "The Truman Show",
        "description": "Un vendeur d'assurance découvre que sa vie tout entière est en fait une émission de télévision.",
        "imageURL": "",
    },
    {
        "filmID": "tt0310203/",
        "category": "film",
        "note": "best",
        "title": "Tais-toi !",
        "description": "Un prisonnier raconte à un autre qu'il a caché une très grosse somme d'argent avant son arrestation. Ensemble, ils parviennent à s'échapper, mais c'est là que leurs aventures ne font que commencer.",
        "imageURL": "",
    },
    {
        "filmID": "tt4537896/",
        "category": "film",
        "note": "love",
        "title": "Undercover: une histoire vraie",
        "description": "L'histoire de l'adolescent Richard Wershe Jr., informateur infiltré pour le FBI dans les années 1980 qui fut finalement arrêté pour trafic de drogue et condamné à vie.",
        "imageURL": "",
    },
    {
        "filmID": "tt10208198/",
        "category": "film",
        "note": "medium",
        "title": "Le Gangster, le flic & l'assassin",
        "description": "Un chef de la mafia et un officier de police responsable d'un commando sanguinaire devront mettre de côté leurs différences pour s'unir dans la poursuite d'un tueur nommé K.",
        "imageURL": "",
    },
    {
        "filmID": "tt0109686/",
        "category": "film",
        "note": "best",
        "title": "Dumb & Dumber",
        "description": "Les aventures à travers champ de deux amis, bon coeurs mais imbéciles.",
        "imageURL": "",
    },
    {
        "filmID": "tt0064116/",
        "category": "film",
        "note": "medium",
        "title": "Il était une fois dans l'Ouest",
        "description": "Un mystérieux inconnu possédant un harmonica s'associe à un desperado notoire pour protéger une jolie veuve d'un assassin sans scrupule travaillant pour le chemin de fer.",
        "imageURL": "",
    },
    {
        "filmID": "tt0060196/",
        "category": "film",
        "note": "medium",
        "title": "Le Bon, la Brute et le Truand",
        "description": "Une arnaque à la chasse aux primes associe deux hommes à une alliance difficile contre un troisième dans une course à la recherche d'une fortune en or enfouie dans un cimetière éloigné.",
        "imageURL": "",
    },
    {
        "filmID": "tt0059578/",
        "category": "film",
        "note": "medium",
        "title": "...et pour quelques dollars de plus",
        "description": "Deux chasseurs de primes partageant les mêmes intentions s'associent pour retrouver un hors-la-loi.",
        "imageURL": "",
    },
    {
        "filmID": "tt1637725/",
        "category": "film",
        "note": "medium",
        "title": "Ted",
        "description": "John Bennett, un homme dont le désir d'enfance de donner vie à son ours en peluche s'est réalisé, doit maintenant décider entre garder la relation avec l'ours ou sa petite amie, Lori.",
        "imageURL": "",
    },
    {
        "filmID": "tt0067355/",
        "category": "film",
        "note": "medium",
        "title": "On l'appelle Trinita",
        "description": "Un tireur paresseux et peu orthodoxe et son frère corpulent et voleur de chevaux défendent une colonie mormone contre un major accapareur de terres, un bandit mexicain et leurs hommes de main.",
        "imageURL": "",
    },
    {
        "filmID": "tt4279012/",
        "category": "animes",
        "note": "love",
        "title": "Death Parade",
        "description": "Après la mort, les humains vont au paradis ou en enfer. Mais pour certains, au moment de leur mort, ils arrivent au Quindecim, un bar fréquenté par le mystérieux Decim aux cheveux blancs.",
        "imageURL": "",
    },
    {
        "filmID": "tt5323662",
        "category": "animes",
        "note": "love",
        "title": "Silent Voice",
        "description": "Un jeune homme est ostracisé par ses camarades de classe après qu'il harcèle une jeune fille sourde au point qu'elle déménage. Des années plus tard, il s'engage sur le chemin de la rédemption.",
        "imageURL": "",
    },
    {
        "filmID": "tt11680468",
        "category": "animes",
        "note": "love",
        "title": "Great Pretender",
        "description": "Un escroc japonais croise la route de son ennemi français et se retrouve mêlé à des complots et desescroqueriesau-delà de ses rêves les plus fous.",
        "imageURL": "",
    },
    {
        "filmID": "tt7078180/",
        "category": "animes",
        "note": "best",
        "title": "Violet Evergarden",
        "description": "Au lendemain d'une grande guerre, Violet Evergarden, une jeune femme ex-soldate, obtient un emploi d'écrivain public et écrit des lettres créant un lien entre différentes personnes.",
        "imageURL": "",
    },
    {
        "filmID": "tt9679542/",
        "category": "animes",
        "note": "best",
        "title": "Dr. Stone",
        "description": "Dans un monde où l'humanité a été pétrifiée, le génie scientifique Senku et son ami musclé Taiju utilisent leurscompétences pour reconstruire la civilisation.",
        "imageURL": "",
    },
    {
        "filmID": "tt0421357",
        "category": "animes",
        "note": "best",
        "title": "Fullmetal Alchemist",
        "description": "Lorsqu'un rituel alchimique raté laisse les frères Edward et Alphonse Elric avec des corps gravementendommagés, ilscommencent à chercher la seule chose qui puisse les sauver; la pierre philosophale légendaire.",
        "imageURL": "",
    },
    {
        "filmID": "tt1355642",
        "category": "animes",
        "note": "medium",
        "title": "Fullmetal Alchemist: Brotherhood",
        "description": "Deux frères en quête d'une Pierre du Philosophe (Philosopher's stone) suite à une tentative de fairerevivre leur mèredécédée a mal tourné et les laisse dans des formes physiques endommagées.",
        "imageURL": "",
    },
    {
        "filmID": "tt3909224",
        "category": "animes",
        "note": "medium",
        "title": "The Seven Deadly Sins: Signs of Holy War",
        "description": "L'histoire des Sept Péchés Capitaux, un groupe de guerriers accusés à tort d'un crime qu'ils n'ont pascommis et quisont maintenant en quête de vengeance.",
        "imageURL": "",
    },
    {
        "filmID": "tt6660498",
        "category": "animes",
        "note": "medium",
        "title": "Devilman: Crybaby",
        "description": "Alors que les démons se réveillent et que l'humanité est en plein bouleversement, un garçon-démonsensible est entraînédans une guerre brutale et dégénérée contre le mal par son mystérieux ami, Ryo.",
        "imageURL": "",
    },
    {
        "filmID": "tt2259737",
        "category": "animes",
        "note": "best",
        "title": "Jormungand",
        "description": "Jormungand focuses on a travelling merchant and a Scandinavian beauty, Koko Hekmatyar. She also has agroup of happyfriends that help Koko avoid the trouble. However, our lovely slice of life is over the moment we findout that Koko isan arms dealer,",
        "imageURL": "",
    },
    {
        "filmID": "tt5537534",
        "category": "animes",
        "note": "medium",
        "title": "Ajin",
        "description": "A high school student discovers he is an Ajin, a demi-human being. He ends up a fugitive on the runbecause of hispowers.",
        "imageURL": "",
    },
    {
        "filmID": "tt13103134",
        "category": "animes",
        "note": "love",
        "title": "Horimiya",
        "description": "Une écolière brillante et un garçon discret se rencontrent et deviennent amis.",
        "imageURL": "",
    },
    {
        "filmID": "tt13196080",
        "category": "animes",
        "note": "medium",
        "title": "Tokyo Revengers",
        "description": "Un loser voyage dans le temps jusqu'à ses années d'école et doit devenir le chef d'un redoutable gang afin de sauverl'amour de sa vie.",
        "imageURL": "",
    },
    {
        "filmID": "tt0423731",
        "category": "animes",
        "note": "medium",
        "title": "Samurai chanpurû",
        "description": "Fuu, une serveuse employée dans une maison de thé, sauve deux maîtres épéistes, Mugen et Jin, de leurexécution pourqu'ils l'aide à trouver le « samurai qui sent le tournesol ».",
        "imageURL": "",
    },
    {
        "filmID": "tt1316554",
        "category": "animes",
        "note": "medium",
        "title": "Black Butler",
        "description": "Un jeune garçon vend son âme à un démon afin de venger la mort de sa famille et de diriger leurentreprise. Le démonprend la forme d'un majordome loyal, tenu de protéger et servir son jeune maître Ciel chaque fois qu'ilest appelé.",
        "imageURL": "",
    },
    {
        "filmID": "tt0877057",
        "category": "animes",
        "note": "medium",
        "title": "Death Note",
        "description": "Un lycéen intelligent se lance dans une croisade secrète afin d'éliminer les criminels du monde aprèsavoir découvert uncahier capable de tuer n'importe quelle personne si son nom y est écrit.",
        "imageURL": "",
    },
    {
        "filmID": "tt5626028",
        "category": "animes",
        "note": "best",
        "title": "My Hero Academia",
        "description": "Un jeune garçon sans super pouvoirs fou de super-héros est bien déterminé à s'inscrire dans uneprestigieuse académie dehéros et à apprendre ce que signifie réellement être un héros.",
        "imageURL": "",
    },
    {
        "filmID": "tt2861424",
        "category": "animes",
        "note": "best",
        "title": "Rick et Morty",
        "description": "Une série animée suivant les exploits d'un super scientifique et de son petit-fils pas très futé.",
        "imageURL": "",
    },
    {
        "filmID": "tt0149460",
        "category": "animes",
        "note": "best",
        "title": "Futurama",
        "description": "Fry, un livreur de pizza se retrouve accidentellement congelé en 1999 et décongelé pour le réveillon du Nouvel An 2999.",
        "imageURL": "",
    },
    {
        "filmID": "tt11126994",
        "category": "animes",
        "note": "best",
        "title": "Arcane",
        "description": "Raconte l'intensification des tensions entre deux villes suite à l'apparition de nouvelles inventions qui menacent de provoquer une véritable révolution.",
        "imageURL": "",
    },
    {
        "filmID": "tt2250192",
        "category": "animes",
        "note": "best",
        "title": "Sword Art Online",
        "description": "En l'an 2022, des milliers de personnes sont prises au piège dans un MMORPG (jeu de rôle massif) et le joueur de loup solitaire, Kirito, travailled pour s'échapper.",
        "imageURL": "",
    },
    {
        "filmID": "tt7978710",
        "category": "animes",
        "note": "best",
        "title": "SAO Alternative : Gun Gale Online",
        "description": "Une étudiante universitaire essaie un jeu de tir Battle Royale en réalité virtuelle et s'impose rapidement comme l'une des joueuses les plus menaçantes de la scène compétitive grâce à son petit avatar ultra-rapide \"LLENN\".",
        "imageURL": "",
    },
    {
        "filmID": "tt7441658",
        "category": "animes",
        "note": "medium",
        "title": "Black Clover",
        "description": "Asta et Yuno ont été abandonnés dans la même église et sont depuis inséparables. Enfants, ils se sont promis qu'ils rivaliseraient l'un contre l'autre afin de voir lequel deviendrait le prochain empereur Magus.",
        "imageURL": "",
    },
    {
        "filmID": "tt0397306",
        "category": "animes",
        "note": "medium",
        "title": "American Dad!",
        "description": "Les escapades aléatoires de Stan Smith, un conservateur et agent de la C.I.A. gérant sa vie de famille et assurant la sécurité de l'Amérique, le tout de la manière la plus absurde possible.",
        "imageURL": "",
    },
    {
        "filmID": "tt4728568",
        "category": "animes",
        "note": "best",
        "title": "DanMachi",
        "description": "Dans la ville d'Orario, où les aventuriers chassent les monstres dans un endroit appelé Dungeon, la vie de Bell Cranel a été sauvée par une épéiste, qui est alors devenue la source de la détermination de Bell à devenir plus fort.",
        "imageURL": "",
    },
    {
        "filmID": "tt14061838/",
        "category": "animes",
        "note": "medium",
        "title": "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat",
        "description": "Lorsque le plus grand assassin du monde arrive à la fin de sa vie, il est envoyé par une déesse pour renaître dans un monde magique et utiliser ses compétences pour sauver ce monde.",
        "imageURL": "",
    },
    {
        "filmID": "tt21209804/",
        "category": "animes",
        "note": "medium",
        "title": "Mashle: Magic and Muscles",
        "description": "C'est dans le monde des magiciens que naît Mash, un garçon qui manque de magie mais qui est la personne la plus forte de son entourage. Son existence et son destin vont changer son monde.",
        "imageURL": "",
    },
    {
        "filmID": "tt5607616/",
        "category": "animes",
        "note": "best",
        "title": "Re: Zero - Starting Life in Another World",
        "description": "Peu après avoir été appelé dans un nouveau monde, Subaru Natsuki et sa nouvelle partenaire sont assassinés brutalement. Mais il se réveille ensuite au même endroit, avec les mêmes voyous, la même fille et la même journée qui se répète.",
        "imageURL": "",
    },
    {
        "filmID": "tt4869896/",
        "category": "animes",
        "note": "medium",
        "title": "Overlord",
        "description": "Un jeune homme est pris au piège dans un jeu vidéo en tant que roi guerrier et cherche à faire de ce nouveau monde son propre empire.",
        "imageURL": "",
    },
    {
        "filmID": "tt2942218/",
        "category": "animes",
        "note": "best",
        "title": "Log Horizon",
        "description": "30,000 Japanese players trapped in MMORPG, unable to log out. Veteran gamer Shiroe leads exploration of this new reality, negotiating with NPCs to bring order to the virtual city of Akihabara.",
        "imageURL": "",
    },
    {
        "filmID": "tt21209876/",
        "category": "animes",
        "note": "best",
        "title": "Ore dake Level Up na Ken",
        "description": "Suit les aventures de Sung Jinwoo dans un monde constamment menacé par des monstres et des forces maléfiques. Au cours de ses combats, Sung passe du statut de chasseur le plus faible de l'humanité à celui de chasseur le plus puissant.",
        "imageURL": "",
    },
    {
        "filmID": "tt2380307/",
        "category": "animes",
        "note": "best",
        "title": "Coco",
        "description": "Miguel, musicien en herbe, entre au pays des morts pour retrouver son arrière-arrière-grand-père, un chanteur légendaire alors qu'il a interdiction de jouer de la musique.",
        "imageURL": "",
    },
    {
        "filmID": "tt5025394/",
        "category": "animes",
        "note": "best",
        "title": "Gangsta",
        "description": "Two handymen take on jobs for both the mob and the police that no one else can handle. Worick and Nicolas work in a town which is full of mafia, hoodlums and prostitutes. They face a challenge after taking on a job of crushing a gang",
        "imageURL": "",
    },
    {
        "filmID": "tt21621494/",
        "category": "animes",
        "note": "best",
        "title": "Gloutons & Dragons",
        "description": "Les sœurs peuvent-elles se réincarner à partir de caca de dragon ? Laios et ses amis Marcille et Chilchuck s'enfoncent dans un donjon sans fin à la recherche de sa sœur déchue, luttant contre les monstres, la famine et la corruption.",
        "imageURL": "",
    },
    {
        "filmID": "tt1528406/",
        "category": "animes",
        "note": "medium",
        "title": "Fairy Tail",
        "description": "Lucy, une aspirante magicienne céleste, devient une amie et une alliée des puissants magiciens Natsu, Grey et Erza, qui font partie de la célèbre (ou mlal famée) guilde des sorciers, Fairy Tail.",
        "imageURL": "",
    },
    {
        "filmID": "tt5311514/",
        "category": "animes",
        "note": "love",
        "title": "Your Name.",
        "description": "Deux étrangers se retrouvent liés d'une étrange manière. Quand une connexion se forme entre eux, la distance sera-t-elle la seule chose qui les séparera?",
        "imageURL": "",
    },
    {
        "filmID": "tt0088509/",
        "category": "animes",
        "note": "medium",
        "title": "Dragon Ball",
        "description": "Son Gokû, un combattant avec une queue de singe, part avec un groupe de personnages étranges à la recherche des Dragon Balls, des cristaux qui peuvent donner tout ce qu'il désire à celui qui les possède.",
        "imageURL": "",
    },
    {
        "filmID": "tt11043632/",
        "category": "animes",
        "note": "medium",
        "title": "Beastars",
        "description": "Dans une école peuplée d'animaux anthropomorphes, un loup humble mais anxieux enquête sur le meurtre soudain d'un camarade de classe, tout en luttant contre ses sentiments pour un petit lapin.",
        "imageURL": "",
    },
    {
        "filmID": "tt14115938/",
        "category": "animes",
        "note": "medium",
        "title": "The Eminence in Shadow",
        "description": "Cid Kagenou aspire à devenir le véritable cerveau derrière tout, à tirer les ficelles et à faire en sorte que ses machinations dirigent toute l'histoire.",
        "imageURL": "",
    },
    {
        "filmID": "tt4958580/",
        "category": "animes",
        "note": "medium",
        "title": "Gate",
        "description": "Une porte apparaît à Tokyo de nos jours et permet l'accès à un monde de fantaisie. Une escouade militaire japonaise est formée pour établir des liens entre les deux mondes.",
        "imageURL": "",
    },
    {
        "filmID": "tt2339875/",
        "category": "animes",
        "note": "medium",
        "title": "Accel World",
        "description": "Haruyuki is an overweight kid and at bottom of food chain at his middle school. Within sci-fi setting of real world he often seeks refuge in a virtual one.",
        "imageURL": "",
    },
    {
        "filmID": "tt3431758/",
        "category": "animes",
        "note": "best",
        "title": "No Game, No Life",
        "description": "Siblings Sora and Shiro make up the most feared team of pro gamers in the world, The Blank. When they manage to beat God himself in a game of chess, they are sent to a world where all disputes are settled with games.",
        "imageURL": "",
    },
    {
        "filmID": "tt13706018/",
        "category": "animes",
        "note": "medium",
        "title": "SPY×FAMILY",
        "description": "Un espion en mission d'infiltration se marie et adopte une enfant dans le cadre de sa couverture. Sa femme et sa fille ont leurs propres secrets, et les trois doivent s'efforcer de rester ensemble.",
        "imageURL": "",
    },
    {
        "filmID": "tt3837246/",
        "category": "animes",
        "note": "best",
        "title": "Assassination Classroom",
        "description": "Une créature puissante prétend détruire la Terre, mais il offre une chance à l'humanité en devenant un professeur qui apprend à ses élèves comment le tuer. Une classe d'assassinat commence.",
        "imageURL": "",
    },
    {
        "filmID": "tt13293588/",
        "category": "animes",
        "note": "medium",
        "title": "Mushoku Tensei: Jobless Reincarnation",
        "description": "Un japonais de 34 ans au chômage est renversé par un camion roulant trop vite et meurt. Il renaît alors sous le nom de Rudeus Greyrat et commence une nouvelle vie pleine d'aventures.",
        "imageURL": "",
    },
    {
        "filmID": "tt1586680",
        "category": "series",
        "note": "best",
        "title": "Shameless",
        "description": "Un homme alcoolique vit dans un état de stupeur permanent alors que ses six enfants font de leur mieuxpour gérer les choses.",
        "imageURL": "",
    },
    {
        "filmID": "tt0898266",
        "category": "series",
        "note": "love",
        "title": "The Big Bang Theory",
        "description": "Une jeune femme emménage dans l'appartement d'en face de deux physiciens brillants mais mal à l'aise ensociété et leur fait se rendre compte qu'ils ignorent presque tout de la vie en dehors de leur laboratoire.",
        "imageURL": "",
    },
    {
        "filmID": "tt6226232",
        "category": "series",
        "note": "love",
        "title": "Young Sheldon",
        "description": "L'enfance du génie Sheldon Cooper qui apparaitra plus tard dans The Big Bang Theory (2007).",
        "imageURL": "",
    },
    {
        "filmID": "tt10048342/",
        "category": "series",
        "note": "love",
        "title": "Le Jeu de la dame",
        "description": "En pleine guerre froide, Beth Harmon est une orpheline prodige des échecs. Suivez-la dans sa quête pour devenir la plus grande joueuse d'échecs du monde tout en affrontant des problèmes d'addiction.",
        "imageURL": "",
    },
    {
        "filmID": "tt1475582",
        "category": "series",
        "note": "best",
        "title": "Sherlock",
        "description": "Une version moderne du célèbre détective et de son partenaire médecin résolvant le crime dans la ville deLondres auXXIème siècle.",
        "imageURL": "",
    },
    {
        "filmID": "tt4158110",
        "category": "series",
        "note": "love",
        "title": "Mr. Robot",
        "description": "Elliot, un jeune ingénieur en cyber sécurité brillant et très instable, devient un personnage clé dans un jeu complexe de domination du monde lorsqu'il tente avec ses alliés mystérieux de renverser la société corrompue pour laquelle il travaille.",
        "imageURL": "",
    },
    {
        "filmID": "tt2543312/",
        "category": "series",
        "note": "love",
        "title": "Halt and Catch Fire",
        "description": "Les innovateurs de la révolution technologique des années 80 qui ont conduit à la société de l'information telle que nous la connaissons.",
        "imageURL": "",
    },
    {
        "filmID": "tt9140554",
        "category": "series",
        "note": "medium",
        "title": "Loki",
        "description": "Loki reprend son rôle de dieu de la malice dans une nouvelle série qui se déroule après les événements de \"Avengers: Endgame\".",
        "imageURL": "",
    },
    {
        "filmID": "tt0903747",
        "category": "series",
        "note": "best",
        "title": "Breaking Bad",
        "description": "Un professeur de chimie de lycée chez qui on a diagnostiqué un cancer du poumon inopérable se tourne vers la fabrication et la vente de méthamphétamine pour assurer l'avenir de sa famille.",
        "imageURL": "",
    },
    {
        "filmID": "tt3032476",
        "category": "series",
        "note": "best",
        "title": "Better Call Saul",
        "description": "Les procès et tribulations de l'avocat criminel Jimmy McGill durant la période précédant la création de son cabinetd'avocats spécialisé dans les centres commerciaux à Albuquerque au Nouveau-Mexique.",
        "imageURL": "",
    },
    {
        "filmID": "tt4063800",
        "category": "series",
        "note": "best",
        "title": "Le Bureau des Légendes",
        "description": "Au bout de six années d'infiltration en Syrie, l'officier de renseignement français Malotru rentre chez lui, où il s'efforce d'oublier son identité d'infiltré, et il forme une jeune recrue et enquête lorsqu'un collègue disparaît en Algérie.",
        "imageURL": "",
    },
    {
        "filmID": "tt1219024",
        "category": "series",
        "note": "love",
        "title": "Castle",
        "description": "Après qu'un tueur en série ait imité les intrigues de ses romans, le célèbre romancier Richard Castle reçoit de la part du maire de New York l'autorisation d'accompagner les enquêteurs d'homicides pour ses recherches.",
        "imageURL": "",
    },
    {
        "filmID": "tt8111088",
        "category": "series",
        "note": "best",
        "title": "The Mandalorian",
        "description": "La série se déroule après la chute de l'Empire et avant l'émergence du Premier Ordre, et suit les épreuves d'un tireur solitaire dans les confins de la galaxie, loin de l'autorité de la Nouvelle République.",
        "imageURL": "",
    },
    {
        "filmID": "tt0212671",
        "category": "series",
        "note": "best",
        "title": "Malcolm",
        "description": "Un jeune adolescent surdoué tente de survivre avec sa famille déréglée et dysfonctionnelle.",
        "imageURL": "",
    },
    {
        "filmID": "tt9288030",
        "category": "series",
        "note": "best",
        "title": "Reacher",
        "description": "Jack Reacher a été arrêté pour meurtre et maintenant la police a besoin de son aide. Basé sur les livres de Lee Child",
        "imageURL": "",
    },
    {
        "filmID": "tt7587890",
        "category": "series",
        "note": "best",
        "title": "The Rookie: le flic de Los Angeles",
        "description": "Pas facile de tout recommencer pour John Nolan qui, après un incident bouleversant, décide de réaliser son rêve de devenir flic et doit faire face aux critiques de ceux qui n'y voient qu'une crise de la quarantaine.",
        "imageURL": "",
    },
    {
        "filmID": "tt0773262",
        "category": "series",
        "note": "medium",
        "title": "Dexter",
        "description": "De jour, Dexter est analyste de traces de sang pour la police de Miami. De nuit, il est tueur en série de meurtriers.",
        "imageURL": "",
    },
    {
        "filmID": "tt10919420",
        "category": "series",
        "note": "love",
        "title": "Squid Game",
        "description": "Tentés par un prix alléchant en cas de victoire, des centaines de joueurs désargentés acceptent de s'affronter lors de jeux pour enfants aux enjeux mortels.",
        "imageURL": "",
    },
    {
        "filmID": "tt1190634/",
        "category": "series",
        "note": "best",
        "title": "The Boys",
        "description": "Une histoire d'action centrée sur une équipe de la CIA chargée de maintenir les super-héros en ligne, par tous les moyens nécessaires.",
        "imageURL": "",
    },
    {
        "filmID": "tt7366338/",
        "category": "series",
        "note": "best",
        "title": "Chernobyl",
        "description": "En avril 1986, une explosion à la centrale nucléaire de Tchernobyl en URSS, devient l'une des pires catastrophes causées par l'homme au monde.",
        "imageURL": "",
    },
    {
        "filmID": "tt11318602/",
        "category": "series",
        "note": "unknow",
        "title": "Don't F**k with Cats: Un tueur trop viral",
        "description": "Une vidéo effroyable pousse un groupe de détectives amateurs à lancer une chasse à l'homme qui va les entrainer dans un univers sombre.",
        "imageURL": "",
    },
    {
        "filmID": "tt2575988/",
        "category": "series",
        "note": "love",
        "title": "Silicon Valley",
        "description": "Suit la lutte de Richard Hendricks, un ingénieur de la Silicon Valley qui tente de créer sa propre société appelée Pied Piper.",
        "imageURL": "",
    },
];

var FilmListType = ["todo", "film", "animes", "series", "towatch"];

function getVideoListType(){
    return FilmListType;
}

function GetVideoList(){
    return filmLinks;
}

function getType(){
    return "film";
}

function getEmoji(FilmListType){
    switch (FilmListType) {
        case 'todo':
            return "⏰";
        case 'film':
            return "🎬";
        case 'animes':
            return "🖌";
        case 'series':
            return "📽";
        case 'towatch':
            return "👀";
        default:
            return "❓";
      }
}

function showFilm(categorie){
    let mainDiv = document.getElementsByClassName("filmsID");
    for(link in filmLinks){
        if(filmLinks[link].category === categorie){
            console.log(filmLinks[link]);

            let div = document.createElement("div");

            let anchor = document.createElement("a");
            let imgTop = document.createElement("img");
            let a = document.createElement("a")
            let img = document.createElement("img");
            let text = document.createElement("p");

            div.className = "card " + getNote(filmLinks[link].note);

            anchor.href = "#" + filmID;
            anchor.class = filmID;

            imgTop.className = "svg";

            a.href = "https://www.imdb.com/title/" + filmLinks[link].filmID;
            a.innerHTML = filmLinks[link].title;

            img.src = filmLinks[link].imageURL;

            text.innerHTML = filmLinks[link].description;

            div.appendChild(imgTop);
            div.appendChild(a);
            div.appendChild(img);
            div.appendChild(text);

            mainDiv[0].appendChild(div);
        }
    }
}

function getNote(note){
    switch(note){
        case 0:
            return "zero";
        case 1:
            return "zero";
        case 2:
            return "bad";
        case 3:
            return "medium";
        case 4:
            return "best";
        case 5:
            return "love";
        default:
            return "unknow";
    }
}