var musiclinks = [
    {
        videoID: "1_Ncsri_quY",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "4rwA8OsYIdU",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "29DieaXfqkg",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "PEar2fUOb6w",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "V_9TtHQhJY8",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "D27Cvj1h_qk",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "lJvRohYSrZM",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "YbKu4o_0kOk",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "JWdXFmy5ga4",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "8DN3PjKG0wE",
        playlist: false,
        top: true,
        categorie: "rap",
    },
    {
        videoID: "aD1IyIBdqjQ",
        playlist: false,
        top: true,
        categorie: "rap",
    },
    {
        videoID: "eWNUtapgAIs",
        playlist: false,
        top: false,
        categorie: "rap",
    },
    {
        videoID: "W5Sq71VTJ9Q",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "rBEc-h3xxC8",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "BZX9ql9uVJs",
        playlist: false,
        top: true,
        categorie: "rap",
    },
    {
        videoID: "R2CzFQpWoLs",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        videoID: "A2zFBoeZrE0",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "-Jeusl_Y_PE",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "bIBDmDJ7SDc",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "E4GHq_yP-ro",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "RSFP-M_QjdQ",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "8rg2vkz72a8",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        text: "⚡☔",
        videoID: "Dnu4qR03Dpc",
        playlist: false,
        top: false,
        categorie: "rain",
    },
    {
        text: "🎹🌁",
        videoID: "Hg-dJOSSAfc",
        playlist: false,
        top: false,
        categorie: "rain",
    },
    {
        text: "☔⚡",
        videoID: "S8wE-SjecT4",
        playlist: false,
        top: true,
        categorie: "rain",
    },
    {
        text: "🎹🌁",
        videoID: "MYTfTKGSRr8",
        playlist: false,
        top: false,
        categorie: "rain",
    },
    {
        text: "",
        videoID: "QHIyFIMu4uQ",
        playlist: false,
        top: false,
        categorie: "rain",
    },
    {
        videoID: "urxeNbBc1nk",
        text: "<a href='https://www.youtube.com/playlist?list=PLLj4tKExmpKL_a-wl0fwMcECIRI0X_4Ty'>PlayList</a>",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        videoID: "6yuDBFn7Suo",
        text: "✝☠",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        text: "Rami Malek's style is over 9999 🖥️",
        videoID: "_tUBCmGBO3A",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "Y4uGmNUR8DQ",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "Kt-tLuszKBA",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        videoID: "WCce-3XMdJs",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "0-1jEhT3umA",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        text: "Sarah Beatriz",
        videoID: "0IKj9atfZvE",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "PLbAFXJC0J5Gbogs-3Jk3nay0sAeAqi3SS",
        playlist: true,
        top: true,
        categorie: "chill",
    },
    {
        videoID: "fmI_Ndrxy14",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        videoID: "Zasx9hjo4WY",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        videoID: "xoWxv2yZXLQ",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        videoID: "E_PbH5y70Tc",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "F5tSoaJ93ac",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        videoID: "oorajmbSJUM",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        videoID: "oaISU5KmTPA",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "Yui-e1VDGM8",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        text: "<a href='https://youtube.com/watch?v=DyDfgMOUjCI'>Original</a>",
        videoID: "3Z4efCGd7TE",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        text: "<a href='https://youtube.com/watch?v=Y2V6yjjPbX0'>Original</a>",
        videoID: "fktD1q8OPa0",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        videoID: "UbQgXeY_zi4",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        text: "神秘的BGM】蒼ノ世界 / 幻想世界の音楽たち",
        videoID: "uqUP66TTXiY",
        playlist: false,
        top: false,
        categorie: "chilljp",
    },
    {
        videoID: "Jg73p9udbAQ",
        playlist: false,
        top: true,
        categorie: "chilljp",
    },
    {
        videoID: "OLAK5uy_mXM3z_ByZFdM3fPV3XaAOYLfkri_b1w7g",
        playlist: true,
        top: false,
        categorie: "chilljp",
    },
    {
        videoID: "jrTMMG0zJyI",
        playlist: false,
        top: false,
        categorie: "chilljp",
    },
    {
        videoID: "goxmvGJkoi0",
        playlist: false,
        top: false,
        categorie: "chilljp",
    },
    {
        videoID: "LUxd9GUJHN8",
        playlist: false,
        top: false,
        categorie: "chilljp",
    },
    {
        videoID: "MgOXIbgPfeI",
        playlist: false,
        top: true,
        categorie: "chilljp",
    },
    {
        videoID: "eSZFIXbqmhs",
        playlist: false,
        top: false,
        categorie: "chilljp",
    },
    {
        videoID: "OntcAJYG29A",
        playlist: false,
        top: false,
        categorie: "chilljp",
    },
    {
        text: "😈",
        videoID: "8zeyRAFMizc",
        playlist: false,
        top: false,
        categorie: "classic",
    },
    {
        text: "Symphonie n°9 philharmonique",
        videoID: "OV0KkYUa6iA",
        playlist: false,
        top: false,
        categorie: "classic",
    },
    {
        text: "⭐🔫",
        videoID: "Z2n9GRUZlCs",
        playlist: false,
        top: true,
        categorie: "classic",
    },
    {
        text: "3. Sequentia: Lacrimosa",
        videoID: "W_kSfXbmwS4",
        playlist: false,
        top: false,
        categorie: "classic",
    },
    {
        videoID: "Szdziw4tI9o",
        playlist: false,
        top: false,
        categorie: "classic",
    },
    {
        videoID: "Kl6R4Ui9blc",
        playlist: false,
        top: true,
        categorie: "classic",
    },
    {
        videoID: "8B_UN9s6SLw",
        playlist: false,
        top: false,
        categorie: "classic",
    },
    {
        text: "Full with Cannons",
        videoID: "VbxgYlcNxE8",
        playlist: false,
        top: false,
        categorie: "classic",
    },
    {
        text: "Romeo and Juliet",
        videoID: "Z_hOR50u7ek",
        playlist: false,
        top: true,
        categorie: "classic",
    },
    {
        videoID: "ZPdk5GaIDjo",
        playlist: false,
        top: true,
        categorie: "classic",
    },
    {
        text: "Midge Ure",
        videoID: "MWCoDpwvWo0",
        playlist: false,
        top: true,
        categorie: "histoire",
    },
    {
        text: "Lindsey Stirling",
        videoID: "EKkzbbLYPuI",
        playlist: false,
        top: true,
        categorie: "histoire",
    },
    {
        text: "Shchedryk",
        videoID: "yx8l0QxV63o",
        playlist: false,
        top: true,
        categorie: "histoire",
    },
    {
        text: "Libera",
        videoID: "SQadcm_dwEM",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        text: "Laura Branigan",
        videoID: "nNEb2k_EmMg",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        text: "Kim Wilde",
        videoID: "8BYKpQ_6GbM",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        text: "R. Wagner",
        videoID: "KMTRqAgLw04",
        playlist: false,
        top: true,
        categorie: "classic",
    },
    {
        text: "A.K.A music name? trool 🤡",
        videoID: "y6120QOlsfU",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        text: "Rick Astley <a href='https://discord.com/vanityurl/dotcom/steakpants/flour/flower/index11.html'>Discord URI</a>",
        videoID: "dQw4w9WgXcQ",
        playlist: false,
        top: true,
        categorie: "histoire",
    },
    {
        videoID: "0nlJuwO0GDs",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        text: "Japanese traditional orchestra",
        videoID: "dx76YPgZviE",
        playlist: false,
        top: true,
        categorie: "histoire",
    },
    {
        videoID: "PD1EXJScA6k",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        text: "Tchaikovsky - 1812 Overture",
        videoID: "PoNvCwnK1Ls",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "wA8E-f1PCQA",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "SreKbSWY4QY",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "gWi_6QmZ2bs",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "ao4RCon11eY",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "EyyzROaB0Ek",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "JzslnqZGSp0",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "qkNKoFfFjYY",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "JRqig6kxmgg",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "UV5pnEkJs9E",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "6sD-s_mrVhM",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "_HwHK-QiXK8",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "SreKbSWY4QY",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "GAHkYbiQU9A",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "HgJ5JSfe1mE",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "sTIUC29Mv5g",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        text: "Super Speed Up",
        videoID: "p5nD4t5MRoE",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        text: "Slowed & Reverb",
        videoID: "mD7ttofMuJU",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        text: "Cursed Crown",
        videoID: "Cr15_9e7-dE",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        text: "Cursed Crown",
        videoID: "OLAK5uy_lnnelnwQcnS0CCsRGpjLGWiVmMEyuIHJk",
        playlist: true,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "xv8qfsARmMo",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "YKX6fDjtrCs",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "8O9l05_YmgM",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "WzUqD9oLnwM",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "iwlcaH9w-6g",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "abwf-BdPFsQ",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "lbcqbVhQhik",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "L5zE7EthV1o",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "DZGq96HznFw",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "wht3KWkM1cs",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "PvxVr2vK3vQ",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "iE6S9UaFo3U",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "1M82zhETc14",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "GDeZetYSAzo",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "--pnreEPBLE",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "RfOH4e8VpBw",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "zLz--CVp-fg",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "ab-WFNS27co",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "qR2QIJdtgiU",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "f-SCahQzK6w",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "Xp4rFiBSAxQ",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "lsWNkpQmJZY",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "PLau9bkm0iK9twhgsxr-bFTEchn_T9O0qW",
        playlist: true,
        top: true,
        categorie: "rap",
    },
    {
        videoID: "PLau9bkm0iK9t1DPKultYqH3q8yWpg-SvR",
        playlist: true,
        top: true,
        categorie: "rap",
    },
    {
        videoID: "PLau9bkm0iK9t470JP18A4a_mI6G_5ffDt",
        playlist: true,
        top: true,
        categorie: "rap",
    },
    {
        videoID: "UULFM9r1xn6s30OnlJWb-jc3Sw",
        text: "XXXTentatcion",
        playlist: true,
        top: false,
        categorie: "rap",
    },
    {
        videoID: "3Hcg-s3nVQw",
        playlist: false,
        top: false,
        categorie: "rap",
    },
    {
        videoID: "tmNpR_xQd8E",
        playlist: false,
        top: false,
        categorie: "rap",
    },
    {
        videoID: "5CzT1DDhKB8",
        playlist: false,
        top: true,
        categorie: "rap",
    },
    {
        videoID: "tExc5EOZ1DY",
        playlist: false,
        top: true,
        categorie: "rap",
    },
    {
        videoID: "2xWkATdMQms",
        playlist: false,
        top: false,
        categorie: "rap",
    },
    {
        videoID: "OLAK5uy_lAo1VUhC2my4SdPRpAn99wdjPhGkoOOE0",
        text: "Kerchak",
        playlist: true,
        top: false,
        categorie: "rap",
    },
    {
        videoID: "PL6TjZZ0C64slw6-FH3fmpKWuawYonS7ZG",
        playlist: true,
        top: false,
        categorie: "rap",
    },
    {
        text: "🍇",
        videoID: "tDJhDfg2jCQ",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        text: "✖🚬",
        videoID: "ZYEIFIZZXTs",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        text: "🚬🌿",
        videoID: "Xx_naluXFMQ",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        text: "ITI - Les Kassos #88",
        videoID: "OAmhM-jWTzg",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        text: "Lien : youtube.com/watch?v=tzx8gCkIKkU",
        videoID: "lBa_oZU_wao",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        text: "PoV Dev's life",
        videoID: "i8lDuo9yqfs",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        text: "⚡",
        videoID: "HZsiToZ8zCI",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        text: "🍾",
        videoID: "QrU1hZxSEXQ",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        text: "Remix",
        videoID: "w2NYYCZAlsk",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        text: "Techno Extended Remix",
        videoID: "j6TwwXvwsKg",
        playlist: false,
        top: true,
        categorie: "trool",
    },
    {
        text: "Original",
        videoID: "h2CHF8TFvwk",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        text: "Édouard Khil",
        videoID: "j2yCfIHFRhI",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        text: "Animation : www.youtube.com/@timyg",
        videoID: "eDW53rXqlRw",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        text: "Michel ❤",
        videoID: "rlarCLhzfoU",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        text: "Eduard Khil",
        videoID: "32UGD0fV45g",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        text: "💩",
        videoID: "lMw3FCXE5ws",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        videoID: "wZTIdnooV-s",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        videoID: "dSPiDFZmAnQ",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "eFSfw6EHvlU",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "fC1HF29n9UA",
        top: false,
        playlist: false,
        categorie: "phonk",
    },
    {
        videoID: "qUwSYxoRhaM",
        top: false,
        playlist: false,
        categorie: "phonk",
    },
    {
        videoID: "W9GXqCBAZb0",
        top: false,
        playlist: false,
        categorie: "phonk",
    },
    {
        videoID: "bsO5G0cY9bc",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "LiovUkBWOos",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "tIelpTlWvBY",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "G1BHtPR8eUI",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "jeeA2MyGXBE",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        videoID: "wZv62ShoStY",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "T1OrhGs7UnI",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        videoID: "L8H7J8VANQo",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "t-hW1eTUUyo",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "D-Lcvp2PHE4",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "sOHPHVJBvf4",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "6Yw8uWNbFMM",
        top: false,
        playlist: false,
        categorie: "rap",
    },
    {
        videoID: "P9v_yA85a1M",
        top: true,
        playlist: false,
        categorie: "rap",
    },
    {
        videoID: "OLAK5uy_mdyVGFbcx-xSVCkG_e-jCj5kXEgRkE0rg",
        playlist: true,
        top: false,
        categorie: "rock",
    },
    {
        videoID: "OLAK5uy_k2kT-piI6Ks23gUXuaBMaiU_MmkESL0hI",
        text: "Vald",
        playlist: true,
        top: false,
        categorie: "rap",
    },
    {
        videoID: "_VuJA-VQRcY",
        playlist: false,
        top: false,
        categorie: "rap",
    },
    {
        videoID: "kc7F34GWpWw",
        playlist: false,
        top: false,
        categorie: "rap",
    },
    {
        videoID: "OLAK5uy_ls_zsXqcs000Aus6LNJPSjUY4DTkQSg5c",
        text: "Freeze Corleone",
        playlist: true,
        top: false,
        categorie: "rap",
    },
    {
        videoID: "UULFCSFseZ6DfCtVO8giGp7GfA",
        text: "Koba LaD",
        playlist: true,
        top: false,
        categorie: "rap",
    },
    {
        videoID: "qrxv0JNVtgY",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        videoID: "0E00Zuayv9Q",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        videoID: "r7qovpFAGrQ",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "ke1wSerqAuU",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "Ym9JY1t_CYk",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "wL8DVHuWI7Y",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "F2xnvyMp8Us",
        text: "<a href='https://youtube.com/watch?v=DF3XjEhJ40Y'>Original</a>",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        text: "Original",
        videoID: "DF3XjEhJ40Y",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        videoID: "Wg4Bcwh5F2U",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "96G0ngElPWk",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "OXPQ_4qanxk",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "7Ua_ilBIx9A",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "w-sQRS-Lc9k",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "5yXdpVCmTGc",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "YyoFFkDIT3k",
        text: "",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "7STMf7kDl-E",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "-BM9QDlc4bE",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "tLJYAMYEUoc",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "u-wEeg4YNoY",
        playlist: false,
        top: true,
        categorie: "chill",
    },
    {
        videoID: "ZEcqHA7dbwM",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "Y2rDb4Ur2dw",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "6POZlJAZsok",
        text: "",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "izGwDsrQ1eQ",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "jAqTQOLPdiw",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "jofNR_WkoCE",
        playlist: false,
        top: false,
        categorie: "trool",
    },
    {
        videoID: "bLM7pGOxeTs",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "UsR08cY8k0A",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "pM3CFiZOU4k",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "OLAK5uy_nUwHtzonyTavwJePfgeD17qQTEWKhjFME",
        text: "Moha La Squale",
        playlist: true,
        top: false,
        categorie: "rap",
    },
    {
        videoID: "OLAK5uy_k_L41kOUwCve-Ahypu7XVmKkG1Q94ezvw",
        text: "MHD",
        playlist: true,
        top: false,
        categorie: "rap",
    },
    {
        videoID: "S9bCLPwzSC0",
        playlist: false,
        top: false,
        categorie: "rap",
    },
    {
        videoID: "DyDfgMOUjCI",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "Y2V6yjjPbX0",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "zj10k3XytQ4",
        playlist: false,
        top: false,
        categorie: "chilljp",
    },
    {
        videoID: "Lgs9QUtWc3M",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "auzfTPp4moA",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "_KztNIg4cvE",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "qsOUv9EzKsg",
        playlist: false,
        top: false,
        categorie: "rain",
    },
    {
        videoID: "eG2XbNpcb2E",
        playlist: false,
        top: true,
        categorie: "classic",
    },
    {
        videoID: "_KEQxsXjZuY",
        text: "Music version",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "PozNmD_FgZY",
        text: "TV version",
        playlist: false,
        top: false,
        categorie: "chill",
    },
    {
        videoID: "PLLkGVD9RIO_BI66nhaUxFS8V72gl1tbyM",
        text: "<a href='https://www.youtube.com/@uni_mafumafu'>@uni_mafumafu</a>",
        playlist: true,
        top: false,
        categorie: "chilljp",
    },
    {
        videoID: "L4oK_b82hxU",
        text: "",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "uT3_6ct-WGE",
        text: "",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "jNd_LxLnIkM",
        text: "",
        playlist: false,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "OLAK5uy_k78kIlOnPe61B7Xv56LDwVBX-hVikh9B8",
        text: "DVRST",
        playlist: true,
        top: true,
        categorie: "phonk",
    },
    {
        videoID: "YXivc8z6PXk",
        text: "",
        playlist: false,
        top: false,
        categorie: "phonk",
    },
    {
        videoID: "y8VfziFZMGY",
        text: "",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "PGNiXGX2nLU",
        text: "",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "9jK-NcRmVcw",
        text: "",
        playlist: false,
        top: false,
        categorie: "histoire",
    },
    {
        videoID: "turCAoWsH-U",
        text: "",
        playlist: false,
        top: false,
        categorie: "phonk",
    }
];

/*
    ,
    {
        videoID: "",
        text: "",
        playlist: false,
        top: false,
        categorie: "",
    }
*/